name: featurehub_sse_client
description: A Dart-IO based client implementation of Server-Sent Events.
version: 2.0.0
repository: https://github.com/featurehub-io/featurehub/tree/master/sdks/dart/dart-eventsource
homepage: https://www.featurehub.io
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: "^1.15.0"
  http: "^0.13.0"
  http_parser: "^4.0.0"
  logging: "^1.0.0"

dev_dependencies:
  test: "^1.16.5"
