/* tslint:disable */
/* eslint-disable */
/**
 * FeatureServiceApi
 * This describes the API clients use for accessing features
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { RolloutStrategyAttribute } from './rollout-strategy-attribute';

  /**
* if the feature in an environment is different from its default, this will be the reason for it. a rollout strategy is defined at the Application level and then applied to a specific feature value. When they are copied to the cache layer they are cloned and the feature value for that strategy is inserted into the clone and those are published.
* @export
* @class RolloutStrategy
*/
export class RolloutStrategy {
  /**
  * 
  * @type {string}
  * @memberof RolloutStrategy
  */
  public id?: string;
  /**
  * names are unique in a case insensitive fashion
  * @type {string}
  * @memberof RolloutStrategy
  */
  public name: string;
  /**
  * value between 0 and 1000000 - for four decimal places
  * @type {number}
  * @memberof RolloutStrategy
  */
  public percentage?: number;
  /**
  * if you don\'t wish to apply percentage based on user id, you can use one or more attributes defined here
  * @type {Array<string>}
  * @memberof RolloutStrategy
  */
  public percentageAttributes?: Array<string>;
  /**
  * the colour used to display the strategy in the UI. indexed table of background/foreground combos.
  * @type {number}
  * @memberof RolloutStrategy
  */
  public colouring?: number;
  /**
  * url to avatar (if any). Not sent to SDK. Preferably a unicorn.
  * @type {string}
  * @memberof RolloutStrategy
  */
  public avatar?: string;
  /**
  * when we attach the RolloutStrategy for Dacha or SSE this lets us push the value out. Only visible in SDK and SSE Edge.
  * @type {any}
  * @memberof RolloutStrategy
  */
  public value?: any | null;
  /**
  * 
  * @type {Array<RolloutStrategyAttribute>}
  * @memberof RolloutStrategy
  */
  public attributes?: Array<RolloutStrategyAttribute>;

  constructor(init?: Partial<RolloutStrategy>) {
    Object.assign(this, init);
  }
}


