/*
 * FeatureServiceApi
 *
 * This describes the API clients use for accessing features
 *
 * The version of the OpenAPI document: 1.1.2
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using IO.FeatureHub.SSE.Client;
using IO.FeatureHub.SSE.Model;
using Environment = IO.FeatureHub.SSE.Model.Environment;

namespace IO.FeatureHub.SSE.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFeatureServiceApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        ///
        /// </summary>
        /// <remarks>
        /// Requests all features for this sdkurl and disconnects
        /// </remarks>
        /// <exception cref="IO.FeatureHub.SSE.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sdkUrl">The SDK urls</param>
        /// <returns>List&lt;Environment&gt;</returns>
        List<Environment> GetFeatureStates (List<string> sdkUrl);

        /// <summary>
        ///
        /// </summary>
        /// <remarks>
        /// Requests all features for this sdkurl and disconnects
        /// </remarks>
        /// <exception cref="IO.FeatureHub.SSE.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sdkUrl">The SDK urls</param>
        /// <returns>ApiResponse of List&lt;Environment&gt;</returns>
        ApiResponse<List<Environment>> GetFeatureStatesWithHttpInfo (List<string> sdkUrl);
        /// <summary>
        ///
        /// </summary>
        /// <remarks>
        /// Updates the feature state if allowed.
        /// </remarks>
        /// <exception cref="IO.FeatureHub.SSE.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sdkUrl">The SDK key for the environment and service account</param>
        /// <param name="featureKey">The key you wish to update/action</param>
        /// <param name="featureStateUpdate"></param>
        /// <returns>object</returns>
        object SetFeatureState (string sdkUrl, string featureKey, FeatureStateUpdate featureStateUpdate);

        /// <summary>
        ///
        /// </summary>
        /// <remarks>
        /// Updates the feature state if allowed.
        /// </remarks>
        /// <exception cref="IO.FeatureHub.SSE.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sdkUrl">The SDK key for the environment and service account</param>
        /// <param name="featureKey">The key you wish to update/action</param>
        /// <param name="featureStateUpdate"></param>
        /// <returns>ApiResponse of object</returns>
        ApiResponse<object> SetFeatureStateWithHttpInfo (string sdkUrl, string featureKey, FeatureStateUpdate featureStateUpdate);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFeatureServiceApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        ///
        /// </summary>
        /// <remarks>
        /// Requests all features for this sdkurl and disconnects
        /// </remarks>
        /// <exception cref="IO.FeatureHub.SSE.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sdkUrl">The SDK urls</param>
        /// <returns>Task of List&lt;Environment&gt;</returns>
        Task<List<Environment>> GetFeatureStatesAsync (List<string> sdkUrl);

        /// <summary>
        ///
        /// </summary>
        /// <remarks>
        /// Requests all features for this sdkurl and disconnects
        /// </remarks>
        /// <exception cref="IO.FeatureHub.SSE.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sdkUrl">The SDK urls</param>
        /// <returns>Task of ApiResponse (List&lt;Environment&gt;)</returns>
        Task<ApiResponse<List<Environment>>> GetFeatureStatesAsyncWithHttpInfo (List<string> sdkUrl);
        /// <summary>
        ///
        /// </summary>
        /// <remarks>
        /// Updates the feature state if allowed.
        /// </remarks>
        /// <exception cref="IO.FeatureHub.SSE.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sdkUrl">The SDK key for the environment and service account</param>
        /// <param name="featureKey">The key you wish to update/action</param>
        /// <param name="featureStateUpdate"></param>
        /// <returns>Task of object</returns>
        Task<object> SetFeatureStateAsync (string sdkUrl, string featureKey, FeatureStateUpdate featureStateUpdate);

        /// <summary>
        ///
        /// </summary>
        /// <remarks>
        /// Updates the feature state if allowed.
        /// </remarks>
        /// <exception cref="IO.FeatureHub.SSE.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sdkUrl">The SDK key for the environment and service account</param>
        /// <param name="featureKey">The key you wish to update/action</param>
        /// <param name="featureStateUpdate"></param>
        /// <returns>Task of ApiResponse (object)</returns>
        Task<ApiResponse<object>> SetFeatureStateAsyncWithHttpInfo (string sdkUrl, string featureKey, FeatureStateUpdate featureStateUpdate);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFeatureServiceApi : IFeatureServiceApiSync, IFeatureServiceApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class FeatureServiceApi : IFeatureServiceApi
    {
        private ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="FeatureServiceApi"/> class.
        /// </summary>
        /// <returns></returns>
        public FeatureServiceApi() : this((string) null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FeatureServiceApi"/> class.
        /// </summary>
        /// <returns></returns>
        public FeatureServiceApi(String basePath)
        {
            this.Configuration = SSE.Client.Configuration.MergeConfigurations(
                GlobalConfiguration.Instance,
                new Configuration { BasePath = basePath }
            );
            this.Client = new ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = SSE.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FeatureServiceApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public FeatureServiceApi(Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = SSE.Client.Configuration.MergeConfigurations(
                GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new ApiClient(this.Configuration.BasePath);
            ExceptionFactory = SSE.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FeatureServiceApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public FeatureServiceApi(ISynchronousClient client,IAsynchronousClient asyncClient, IReadableConfiguration configuration)
        {
            if(client == null) throw new ArgumentNullException("client");
            if(asyncClient == null) throw new ArgumentNullException("asyncClient");
            if(configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = SSE.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IReadableConfiguration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  Requests all features for this sdkurl and disconnects
        /// </summary>
        /// <exception cref="IO.FeatureHub.SSE.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sdkUrl">The SDK urls</param>
        /// <returns>List&lt;Environment&gt;</returns>
        public List<Environment> GetFeatureStates (List<string> sdkUrl)
        {
             ApiResponse<List<Environment>> localVarResponse = GetFeatureStatesWithHttpInfo(sdkUrl);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Requests all features for this sdkurl and disconnects
        /// </summary>
        /// <exception cref="IO.FeatureHub.SSE.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sdkUrl">The SDK urls</param>
        /// <returns>ApiResponse of List&lt;Environment&gt;</returns>
        public ApiResponse< List<Environment> > GetFeatureStatesWithHttpInfo (List<string> sdkUrl)
        {
            // verify the required parameter 'sdkUrl' is set
            if (sdkUrl == null)
                throw new ApiException(400, "Missing required parameter 'sdkUrl' when calling FeatureServiceApi->GetFeatureStates");

            RequestOptions localVarRequestOptions = new RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("multi", "sdkUrl", sdkUrl));


            // make the HTTP request
            var localVarResponse = this.Client.Get< List<Environment> >("/features/", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetFeatureStates", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Requests all features for this sdkurl and disconnects
        /// </summary>
        /// <exception cref="IO.FeatureHub.SSE.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sdkUrl">The SDK urls</param>
        /// <returns>Task of List&lt;Environment&gt;</returns>
        public async Task<List<Environment>> GetFeatureStatesAsync (List<string> sdkUrl)
        {
             ApiResponse<List<Environment>> localVarResponse = await GetFeatureStatesAsyncWithHttpInfo(sdkUrl);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Requests all features for this sdkurl and disconnects
        /// </summary>
        /// <exception cref="IO.FeatureHub.SSE.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sdkUrl">The SDK urls</param>
        /// <returns>Task of ApiResponse (List&lt;Environment&gt;)</returns>
        public async Task<ApiResponse<List<Environment>>> GetFeatureStatesAsyncWithHttpInfo (List<string> sdkUrl)
        {
            // verify the required parameter 'sdkUrl' is set
            if (sdkUrl == null)
                throw new ApiException(400, "Missing required parameter 'sdkUrl' when calling FeatureServiceApi->GetFeatureStates");


            RequestOptions localVarRequestOptions = new RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);

            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);

            localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("multi", "sdkUrl", sdkUrl));


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<Environment>>("/features/", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetFeatureStates", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Updates the feature state if allowed.
        /// </summary>
        /// <exception cref="IO.FeatureHub.SSE.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sdkUrl">The SDK key for the environment and service account</param>
        /// <param name="featureKey">The key you wish to update/action</param>
        /// <param name="featureStateUpdate"></param>
        /// <returns>object</returns>
        public object SetFeatureState (string sdkUrl, string featureKey, FeatureStateUpdate featureStateUpdate)
        {
             ApiResponse<object> localVarResponse = SetFeatureStateWithHttpInfo(sdkUrl, featureKey, featureStateUpdate);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Updates the feature state if allowed.
        /// </summary>
        /// <exception cref="IO.FeatureHub.SSE.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sdkUrl">The SDK key for the environment and service account</param>
        /// <param name="featureKey">The key you wish to update/action</param>
        /// <param name="featureStateUpdate"></param>
        /// <returns>ApiResponse of object</returns>
        public ApiResponse< object > SetFeatureStateWithHttpInfo (string sdkUrl, string featureKey, FeatureStateUpdate featureStateUpdate)
        {
            // verify the required parameter 'sdkUrl' is set
            if (sdkUrl == null)
                throw new ApiException(400, "Missing required parameter 'sdkUrl' when calling FeatureServiceApi->SetFeatureState");

            // verify the required parameter 'featureKey' is set
            if (featureKey == null)
                throw new ApiException(400, "Missing required parameter 'featureKey' when calling FeatureServiceApi->SetFeatureState");

            // verify the required parameter 'featureStateUpdate' is set
            if (featureStateUpdate == null)
                throw new ApiException(400, "Missing required parameter 'featureStateUpdate' when calling FeatureServiceApi->SetFeatureState");

            RequestOptions localVarRequestOptions = new RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("sdkUrl", ClientUtils.ParameterToString(sdkUrl)); // path parameter
            localVarRequestOptions.PathParameters.Add("featureKey", ClientUtils.ParameterToString(featureKey)); // path parameter
            localVarRequestOptions.Data = featureStateUpdate;


            // make the HTTP request
            var localVarResponse = this.Client.Put< object >("/features/{sdkUrl}/{featureKey}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SetFeatureState", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Updates the feature state if allowed.
        /// </summary>
        /// <exception cref="IO.FeatureHub.SSE.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sdkUrl">The SDK key for the environment and service account</param>
        /// <param name="featureKey">The key you wish to update/action</param>
        /// <param name="featureStateUpdate"></param>
        /// <returns>Task of object</returns>
        public async Task<object> SetFeatureStateAsync (string sdkUrl, string featureKey, FeatureStateUpdate featureStateUpdate)
        {
             ApiResponse<object> localVarResponse = await SetFeatureStateAsyncWithHttpInfo(sdkUrl, featureKey, featureStateUpdate);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Updates the feature state if allowed.
        /// </summary>
        /// <exception cref="IO.FeatureHub.SSE.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sdkUrl">The SDK key for the environment and service account</param>
        /// <param name="featureKey">The key you wish to update/action</param>
        /// <param name="featureStateUpdate"></param>
        /// <returns>Task of ApiResponse (object)</returns>
        public async Task<ApiResponse<object>> SetFeatureStateAsyncWithHttpInfo (string sdkUrl, string featureKey, FeatureStateUpdate featureStateUpdate)
        {
            // verify the required parameter 'sdkUrl' is set
            if (sdkUrl == null)
                throw new ApiException(400, "Missing required parameter 'sdkUrl' when calling FeatureServiceApi->SetFeatureState");

            // verify the required parameter 'featureKey' is set
            if (featureKey == null)
                throw new ApiException(400, "Missing required parameter 'featureKey' when calling FeatureServiceApi->SetFeatureState");

            // verify the required parameter 'featureStateUpdate' is set
            if (featureStateUpdate == null)
                throw new ApiException(400, "Missing required parameter 'featureStateUpdate' when calling FeatureServiceApi->SetFeatureState");


            RequestOptions localVarRequestOptions = new RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);

            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);

            localVarRequestOptions.PathParameters.Add("sdkUrl", ClientUtils.ParameterToString(sdkUrl)); // path parameter
            localVarRequestOptions.PathParameters.Add("featureKey", ClientUtils.ParameterToString(featureKey)); // path parameter
            localVarRequestOptions.Data = featureStateUpdate;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<object>("/features/{sdkUrl}/{featureKey}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SetFeatureState", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
