openapi: 3.0.1
info:
  title: Feature Messaging API
  description: This is an OpenAPI document for featurehub messaging data. It is used to publish feature updates to messaging listeners.
  version: "1.3.0"
paths:
  /v2/fake:
    get:
      operationId: fakeApi
      tags:
        - FeatureMessagingService
      description: "this is just a holder, it is not generated"
      responses:
        200:
          description: "yay"
components:
  schemas:
    FeatureMessagingUpdate:
      x-cloudevent-type: messaging-feature-v1
      x-cloudevent-subject: io.featurehub.events.messaging
      x-publish-include: messaging
      x-package: io.featurehub.messaging.model
      x-implements: io.featurehub.events.messaging.AdditionalInfoMessage
      description: "Changes made to a specific feature and optionally value and who changed it. This will currently only occur when a feature value changes, not on feature creation or deletion."
      type: object
      properties:
        environmentName:
          x-basename: eName
          type: string
        environmentId:
          x-basename: eId
          type: string
          format: uuid
        portfolioName:
          x-basename: pName
          type: string
        portfolioId:
          x-basename: pId
          type: string
          format: uuid
        orgName:
          x-basename: oName
          type: string
        organizationId:
          x-basename: oId
          type: string
          format: uuid
        appName:
          x-basename: aName
          type: string
        applicationId:
          x-basename: aId
          type: string
          format: uuid
        whenUpdated:
          type: string
          format: date-time
        whoUpdatedId:
          type: string
          format: uuid
          description: "The ID of the person who updated the feature"
        whoUpdated:
          type: string
          description: Name of the user who made the change to the feature
        featureName:
          description: "The name of the feature"
          x-basename: fName
          type: string
        featureKey:
          x-basename: fKey
          description: "Feature key that got updated"
          type: string
        featureId:
          x-basename: fId
          description: "Id of the Feature that got updated"
          type: string
          format: uuid
        featureValueId:
          description: "Id of Feature value that got updated"
          type: string
          format: uuid
          nullable: true
        operation:
          description: "The basic operation performed, create a feature, update a feature in an environment, delete a feature"
        featureValueType:
          description: "Type of the feature value"
          allOf:
            - $ref: "#/components/schemas/FeatureValueType"
        desc:
          description: "Feature description"
          nullable: true
          type: string
        link:
          description: "Link associated with feature (if any)"
          nullable: true
          type: string
        version:
          nullable: true
          allOf:
            - $ref: "#/components/schemas/FeatureVersion"
        featureValueUpdated:
          nullable: true
          #description: "Feature value changes"
          allOf:
            - $ref: '#/components/schemas/MessagingFeatureValueUpdate'
        lockUpdated:
          nullable: true
          #description: "Lock changes"
          allOf:
            - $ref: '#/components/schemas/MessagingLockUpdate'
        retiredUpdated:
          nullable: true
          #description: "Retired changes"
          allOf:
            - $ref: '#/components/schemas/MessagingRetiredUpdate'
        strategiesUpdated:
          nullable: true
          description: "Strategies changes"
          type: array
          items:
            $ref: '#/components/schemas/MessagingStrategyUpdate'
        applicationStrategiesUpdated:
          nullable: true
          description: "Strategies changes"
          type: array
          items:
            $ref: '#/components/schemas/MessagingStrategyUpdate'
        strategiesReordered:
          nullable: true
          #description: "Strategies reorder changes"
          allOf:
            - $ref: '#/components/schemas/MessagingStrategiesReorder'
        applicationStrategiesReordered:
          nullable: true
          #description: "Strategies reorder changes"
          allOf:
            - $ref: '#/components/schemas/MessagingStrategiesReorder'
        additionalInfo:
          description: "Any additional info, webhook headers etc"
          nullable: true
          type: string
          additionalProperties:
            type: string
    FeatureVersion:
      type: object
      description: "Describes the previous and current versions"
      properties:
        prev:
          description: "Prior version - version we are changing"
          type: integer
          format: int64
          nullable: true
        curr:
          description: "Current version, version we are changing to"
          type: integer
          format: int64
    MessagingFeatureValueUpdate:
      x-package: io.featurehub.messaging.model
      type: object
      description: "Feature value changes, if any"
      required:
        - updated
        - previous
      properties:
        updated:
          description: "Updated feature value"
        previous:
          description: "Previous feature value"
    MessagingLockUpdate:
      x-package: io.featurehub.messaging.model
      type: object
      description: "Lock value changes, if any"
      required:
        - updated
        - previous
      properties:
        updated:
          type: boolean
          description: "Updated lock value"
        previous:
          type: boolean
          description: "Previous lock value"
    MessagingRetiredUpdate:
      x-package: io.featurehub.messaging.model
      type: object
      description: "Retired value changes, if any"
      required:
        - updated
        - previous
      properties:
        updated:
          type: boolean
          description: "Updated retired value"
        previous:
          type: boolean
          description: "Previous retired value"

    MessagingStrategiesReorder:
      x-package: io.featurehub.messaging.model
      type: object
      description: "Strategies reorders, if any"
      required:
        - reordered
        - previous
      properties:
        reordered:
          type: array
          items:
            $ref: '#/components/schemas/MessagingRolloutStrategy'
          description: "Reordered strategies"
        previous:
          type: array
          items:
            $ref: '#/components/schemas/MessagingRolloutStrategy'
          description: "Previous strategies"

    MessagingStrategyUpdate:
      x-package: io.featurehub.messaging.model
      type: object
      required:
        - updateType
      properties:
        updateType:
          $ref: '#/components/schemas/StrategyUpdateType'
        oldStrategy:
          nullable: true
          allOf:
            - $ref: '#/components/schemas/MessagingRolloutStrategy'
        newStrategy:
          nullable: true
          allOf:
            - $ref: '#/components/schemas/MessagingRolloutStrategy'
    StrategyUpdateType:
      x-package: io.featurehub.messaging.model
      type: string
      enum:
        - ADDED
        - CHANGED
        - DELETED

    MessagingRolloutStrategy:
      x-package: io.featurehub.messaging.model
      description: "Updated rollout strategy"
      allOf:
        - $ref: "#/components/schemas/BaseRolloutStrategy"
        - type: object
          properties:
            name:
              description: "strategy name"
              type: string
            id:
              description: "strategy id"
              type: string
            attributes:
              type: array
              items:
                $ref: "#/components/schemas/MessagingRolloutStrategyAttribute"

    MessagingRolloutStrategyAttribute:
      x-package: io.featurehub.messaging.model
      allOf:
        - $ref: "#/components/schemas/RolloutStrategyAttribute"
        - type: object
          required:
            - conditional
            - fieldName
            - type
