-- apply changes
create table fh_after_mig_job (
  id                            integer generated by default as identity not null,
  job_name                      varchar(255) not null,
  completed                     boolean default false not null,
  constraint pk_fh_after_mig_job primary key (id)
);

create table fh_fv_version (
  id                            uuid not null,
  version                       bigint not null,
  fk_who_updated                uuid,
  feature_state                 varchar(8),
  default_value                 clob,
  locked                        boolean default false not null,
  rollout_strat                 clob,
  retired                       boolean default false not null,
  feature_id                    uuid not null,
  shared_strat                  clob,
  when_created                  timestamp not null,
  constraint ck_fh_fv_version_feature_state check ( feature_state in ('DISABLED','READY','ENABLED')),
  constraint pk_fh_fv_version primary key (id,version)
);

-- foreign keys and indices
create index ix_fh_fv_version_fk_who_updated on fh_fv_version (fk_who_updated);
alter table fh_fv_version add constraint fk_fh_fv_version_fk_who_updated foreign key (fk_who_updated) references fh_person (id) on delete set null on update restrict;

create index ix_fh_fv_version_feature_id on fh_fv_version (feature_id);
alter table fh_fv_version add constraint fk_fh_fv_version_feature_id foreign key (feature_id) references fh_app_feature (id) on delete restrict on update restrict;

insert into fh_after_mig_job(id, completed, job_name) values (1, false, 'upgrade-rollout-strategies');
