# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
enable-beta-ecosystems: true

updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/backend" # Location of package manifests
    open-pull-requests-limit: 0  # only open security PRs
    schedule:
      interval: "daily"

  - package-ecosystem: "pub"
    directory: "/admin-frontend/open_admin_app"
    open-pull-requests-limit: 0  # only open security PRs
    schedule:
      interval: "daily"

