name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    label: 'enhancement'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '📝 Documentation'
    label: 'docs'
  - title: '📌 Dependencies'
    label: 'dependencies'
  - title: '🧰 Platform Improvements'
    label: 'improvement'
include-labels:
  - 'enhancement'
  - 'bug'
  - 'docs'
  - 'dependencies'
  - 'improvement'
autolabeler:
  - label: 'docs'
    branch:
      - '/docs\/.+/'
#     files:
#       - '*.md'
#       - '*.adoc'
    title:
      - '/Docs/i'  
  - label: 'bug'
    branch:
      - '/fix\/.+/'
      - '/bugfix\/.+/'
    title:
      - '/Fix/i'
      - '/Bugfix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
    title:
      - '/Feature/i'
  - label: 'dependencies'
    branch:
      - '/dependencies\/.+/'
      - '/dependency\/.+/'
    title:
      - '/Dependency/i'
      - '/Dependencies/i'
  - label: 'improvement'
    branch:
      - '/improvement\/.+/'
    title:
      - '/Improvement/i'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes
  $CHANGES
