version: '3.1'

services:
  postgres:

  party-server:
    image: featurehub/party-server:0.0.1
    restart: always
    volumes:
      - featurehub-h2-data:/db
    ports:
      - 8085:8085
volumes:
  featurehub-h2-data:
