= How to do the open source release

There are a few stages:

- ensure the base images are built (rare)
- ensure the artifacts are build (all the backend, every time)
- build all the front end images with the right tags (every time)

== Base Images

As of time of writing, the open source version is only releasable locally. It relies on a couple of base images
existing, so to release you should build these. To do so, 

----
cd pipeline/build/base_mr
sh make-image.sh
cd ../base_party
sh make-image.sh
----
This is only required when the base image is changed, which is fairly rare.

Then make sure you have the latest flutter_web image builder:

----
docker pull featurehub/flutter_web:1.3
----

== Artifacts & Docker images

and now its a case of simply building everything.

so from the top level directory do:

----
sh build_all_and_test.sh
cd backend
sh build.sh 1.3.5
----

where 1.3.5 is the version you want everything to be tagged as. When it is a release candidate, you're not sure
it will actually release, consider putting an -RC1 or -RC2 on it to ensure you don't get the releases confused. 

NOTE: Any build you do will *ALSO* be tagged as `:latest`.

== Checking the featurehub installs

To run the `featurehub-installs`, go through each one, one by one and do a `docker-compose up` and check them.
Because the build tagged everything latest, you don't have to worry

== All good? time to push

in the backups folder is a script that will tag all the versions you built as latest and push everything.

----
sh push.sh 1.4.0
----

