version: '3.1'

services:
  party-server:
    image: featurehub/mr:0.0.1
    restart: always
    volumes:
      - featurehub-h2-mr-data:/db
    ports:
      - 8085:8085
volumes:
  featurehub-h2-mr-data:
