steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - 'git rev-parse HEAD > current-ref'
  - name: 'gcr.io/cloud-builders/git'
    args:
      - clone
      - 'https://github.com/featurehub-io/featurehub.git'
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - 'cd featurehub;git checkout -b workbranch `cat ../current-ref`'
  - name: 'us-central1-docker.pkg.dev/demohub-283022/demohub/build-images/maven:3.6.3-jdk-11'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - 'cd featurehub/backend && mvn -s ../pipeline/m2/settings.xml --no-transfer-progress install -f pom-first.xml'
# this next section deals with the Admin front-end. This is expensive to build every time, so we need to detect if
# it or its upstream dependencies have changed and only build it then
  - name: 'us-central1-docker.pkg.dev/demohub-283022/demohub/build-images/maven:3.6.3-jdk-11'
    entrypoint: '/bin/sh'
    # if anything in the front-end list of stuff has changed, touch the file `build-frontend` and the next two
    # steps will cause everything necessary to build. The pom-front-end.xml is just a dependency tree and change checker.
    args:
      - '-c'
      - 'cd featurehub && mvn -s pipeline/m2/settings.xml --no-transfer-progress validate -f pom-front-end.xml && touch front-end-changed.projects && CHANGED=`wc -l < front-end-changed.projects|xargs` && if [ "$CHANGED" != "0" ]; then touch build-frontend; fi'
#  - name: 'us-central1-docker.pkg.dev/demohub-283022/demohub/build-images/maven:3.6.3-jdk-11'
#    entrypoint: '/bin/sh'
#    args:
#      - '-c'
#      - 'cd featurehub && ls -l'
  - name: 'us-central1-docker.pkg.dev/demohub-283022/demohub/build-images/maven:3.6.3-jdk-11'
    entrypoint: '/bin/sh'
    # these are required for the flutter build to work
    args:
      - '-c'
      - 'cd featurehub && if [ -f build-frontend ]; then mvn -s pipeline/m2/settings.xml --no-transfer-progress install -f admin-frontend/app_mr_layer/pom.xml; else true; fi'
  - name: 'us-central1-docker.pkg.dev/demohub-283022/demohub/build-images/flutter-build:d9044a8a61e4d7d0afbd4fe8bad6d40762c289dd'
    # the version of flutter-build refers to the commit message. It is the base image used to build the front end. This will *only build the artifacts and
    # not generate the installable file required to build the docker images. That is not done in this pipeline (only when building the actual docker images)
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - 'cd featurehub && chmod u+x admin-frontend/pipeline-build.sh && admin-frontend/pipeline-build.sh'
  - name: 'us-central1-docker.pkg.dev/demohub-283022/demohub/build-images/maven:3.6.3-jdk-11'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - 'cd featurehub && if [ -f all-build ]; then mvn -s pipeline/m2/settings.xml --no-transfer-progress install -f pom.xml; else true; fi'
  - name: 'us-central1-docker.pkg.dev/demohub-283022/demohub/build-images/maven:3.6.3-jdk-11'
    # run partial build if special "all-build" file is missing
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - 'cd featurehub && if [ ! -f all-build ]; then mvn -s pipeline/m2/settings.xml --no-transfer-progress install -Dgib.disable=false -Dgib.referenceBranch=master -f pom.xml; else true; fi'




