part of featurehub_client_api.api;

enum StrategyAttributeCountryName {
  afghanistan,
  albania,
  algeria,
  andorra,
  angola,
  antiguaAndBarbuda,
  argentina,
  armenia,
  australia,
  austria,
  azerbaijan,
  theBahamas,
  bahrain,
  bangladesh,
  barbados,
  belarus,
  belgium,
  belize,
  benin,
  bhutan,
  bolivia,
  bosniaAndHerzegovina,
  botswana,
  brazil,
  brunei,
  bulgaria,
  burkinaFaso,
  burundi,
  caboVerde,
  cambodia,
  cameroon,
  canada,
  centralAfricanRepublic,
  chad,
  chile,
  china,
  colombia,
  comoros,
  congoDemocraticRepublicOfThe,
  congoRepublicOfThe,
  costaRica,
  coteDivoire,
  croatia,
  cuba,
  cyprus,
  czechRepublic,
  denmark,
  djibouti,
  dominica,
  dominicanRepublic,
  eastTimor,
  ecuador,
  egypt,
  elSalvador,
  equatorialGuinea,
  eritrea,
  estonia,
  eswatini,
  ethiopia,
  fiji,
  finland,
  france,
  gabon,
  theGambia,
  georgia,
  germany,
  ghana,
  greece,
  grenada,
  guatemala,
  guinea,
  guineaBissau,
  guyana,
  haiti,
  honduras,
  hungary,
  iceland,
  india,
  indonesia,
  iran,
  iraq,
  ireland,
  israel,
  italy,
  jamaica,
  japan,
  jordan,
  kazakhstan,
  kenya,
  kiribati,
  koreaNorth,
  koreaSouth,
  kosovo,
  kuwait,
  kyrgyzstan,
  laos,
  latvia,
  lebanon,
  lesotho,
  liberia,
  libya,
  liechtenstein,
  lithuania,
  luxembourg,
  madagascar,
  malawi,
  malaysia,
  maldives,
  mali,
  malta,
  marshallIslands,
  mauritania,
  mauritius,
  mexico,
  micronesiaFederatedStatesOf,
  moldova,
  monaco,
  mongolia,
  montenegro,
  morocco,
  mozambique,
  myanmar,
  namibia,
  nauru,
  nepal,
  netherlands,
  newZealand,
  nicaragua,
  niger,
  nigeria,
  northMacedonia,
  norway,
  oman,
  pakistan,
  palau,
  panama,
  papuaNewGuinea,
  paraguay,
  peru,
  philippines,
  poland,
  portugal,
  qatar,
  romania,
  russia,
  rwanda,
  saintKittsAndNevis,
  saintLucia,
  saintVincentAndTheGrenadines,
  samoa,
  sanMarino,
  saoTomeAndPrincipe,
  saudiArabia,
  senegal,
  serbia,
  seychelles,
  sierraLeone,
  singapore,
  slovakia,
  slovenia,
  solomonIslands,
  somalia,
  southAfrica,
  spain,
  sriLanka,
  sudan,
  sudanSouth,
  suriname,
  sweden,
  switzerland,
  syria,
  taiwan,
  tajikistan,
  tanzania,
  thailand,
  togo,
  tonga,
  trinidadAndTobago,
  tunisia,
  turkey,
  turkmenistan,
  tuvalu,
  uganda,
  ukraine,
  unitedArabEmirates,
  unitedKingdom,
  unitedStates,
  uruguay,
  uzbekistan,
  vanuatu,
  vaticanCity,
  venezuela,
  vietnam,
  yemen,
  zambia,
  zimbabwe
}

extension StrategyAttributeCountryNameExtension
    on StrategyAttributeCountryName {
  String get name => toMap[this];

  // you have to call this extension class to use this as this is not yet supported
  static StrategyAttributeCountryName type(String name) => fromMap[name];

  static Map<String, StrategyAttributeCountryName> fromMap = {
    'afghanistan': StrategyAttributeCountryName.afghanistan,
    'albania': StrategyAttributeCountryName.albania,
    'algeria': StrategyAttributeCountryName.algeria,
    'andorra': StrategyAttributeCountryName.andorra,
    'angola': StrategyAttributeCountryName.angola,
    'antigua_and_barbuda': StrategyAttributeCountryName.antiguaAndBarbuda,
    'argentina': StrategyAttributeCountryName.argentina,
    'armenia': StrategyAttributeCountryName.armenia,
    'australia': StrategyAttributeCountryName.australia,
    'austria': StrategyAttributeCountryName.austria,
    'azerbaijan': StrategyAttributeCountryName.azerbaijan,
    'the_bahamas': StrategyAttributeCountryName.theBahamas,
    'bahrain': StrategyAttributeCountryName.bahrain,
    'bangladesh': StrategyAttributeCountryName.bangladesh,
    'barbados': StrategyAttributeCountryName.barbados,
    'belarus': StrategyAttributeCountryName.belarus,
    'belgium': StrategyAttributeCountryName.belgium,
    'belize': StrategyAttributeCountryName.belize,
    'benin': StrategyAttributeCountryName.benin,
    'bhutan': StrategyAttributeCountryName.bhutan,
    'bolivia': StrategyAttributeCountryName.bolivia,
    'bosnia_and_herzegovina': StrategyAttributeCountryName.bosniaAndHerzegovina,
    'botswana': StrategyAttributeCountryName.botswana,
    'brazil': StrategyAttributeCountryName.brazil,
    'brunei': StrategyAttributeCountryName.brunei,
    'bulgaria': StrategyAttributeCountryName.bulgaria,
    'burkina_faso': StrategyAttributeCountryName.burkinaFaso,
    'burundi': StrategyAttributeCountryName.burundi,
    'cabo_verde': StrategyAttributeCountryName.caboVerde,
    'cambodia': StrategyAttributeCountryName.cambodia,
    'cameroon': StrategyAttributeCountryName.cameroon,
    'canada': StrategyAttributeCountryName.canada,
    'central_african_republic':
        StrategyAttributeCountryName.centralAfricanRepublic,
    'chad': StrategyAttributeCountryName.chad,
    'chile': StrategyAttributeCountryName.chile,
    'china': StrategyAttributeCountryName.china,
    'colombia': StrategyAttributeCountryName.colombia,
    'comoros': StrategyAttributeCountryName.comoros,
    'congo_democratic_republic_of_the':
        StrategyAttributeCountryName.congoDemocraticRepublicOfThe,
    'congo_republic_of_the': StrategyAttributeCountryName.congoRepublicOfThe,
    'costa_rica': StrategyAttributeCountryName.costaRica,
    'cote_divoire': StrategyAttributeCountryName.coteDivoire,
    'croatia': StrategyAttributeCountryName.croatia,
    'cuba': StrategyAttributeCountryName.cuba,
    'cyprus': StrategyAttributeCountryName.cyprus,
    'czech_republic': StrategyAttributeCountryName.czechRepublic,
    'denmark': StrategyAttributeCountryName.denmark,
    'djibouti': StrategyAttributeCountryName.djibouti,
    'dominica': StrategyAttributeCountryName.dominica,
    'dominican_republic': StrategyAttributeCountryName.dominicanRepublic,
    'east_timor': StrategyAttributeCountryName.eastTimor,
    'ecuador': StrategyAttributeCountryName.ecuador,
    'egypt': StrategyAttributeCountryName.egypt,
    'el_salvador': StrategyAttributeCountryName.elSalvador,
    'equatorial_guinea': StrategyAttributeCountryName.equatorialGuinea,
    'eritrea': StrategyAttributeCountryName.eritrea,
    'estonia': StrategyAttributeCountryName.estonia,
    'eswatini': StrategyAttributeCountryName.eswatini,
    'ethiopia': StrategyAttributeCountryName.ethiopia,
    'fiji': StrategyAttributeCountryName.fiji,
    'finland': StrategyAttributeCountryName.finland,
    'france': StrategyAttributeCountryName.france,
    'gabon': StrategyAttributeCountryName.gabon,
    'the_gambia': StrategyAttributeCountryName.theGambia,
    'georgia': StrategyAttributeCountryName.georgia,
    'germany': StrategyAttributeCountryName.germany,
    'ghana': StrategyAttributeCountryName.ghana,
    'greece': StrategyAttributeCountryName.greece,
    'grenada': StrategyAttributeCountryName.grenada,
    'guatemala': StrategyAttributeCountryName.guatemala,
    'guinea': StrategyAttributeCountryName.guinea,
    'guinea_bissau': StrategyAttributeCountryName.guineaBissau,
    'guyana': StrategyAttributeCountryName.guyana,
    'haiti': StrategyAttributeCountryName.haiti,
    'honduras': StrategyAttributeCountryName.honduras,
    'hungary': StrategyAttributeCountryName.hungary,
    'iceland': StrategyAttributeCountryName.iceland,
    'india': StrategyAttributeCountryName.india,
    'indonesia': StrategyAttributeCountryName.indonesia,
    'iran': StrategyAttributeCountryName.iran,
    'iraq': StrategyAttributeCountryName.iraq,
    'ireland': StrategyAttributeCountryName.ireland,
    'israel': StrategyAttributeCountryName.israel,
    'italy': StrategyAttributeCountryName.italy,
    'jamaica': StrategyAttributeCountryName.jamaica,
    'japan': StrategyAttributeCountryName.japan,
    'jordan': StrategyAttributeCountryName.jordan,
    'kazakhstan': StrategyAttributeCountryName.kazakhstan,
    'kenya': StrategyAttributeCountryName.kenya,
    'kiribati': StrategyAttributeCountryName.kiribati,
    'korea_north': StrategyAttributeCountryName.koreaNorth,
    'korea_south': StrategyAttributeCountryName.koreaSouth,
    'kosovo': StrategyAttributeCountryName.kosovo,
    'kuwait': StrategyAttributeCountryName.kuwait,
    'kyrgyzstan': StrategyAttributeCountryName.kyrgyzstan,
    'laos': StrategyAttributeCountryName.laos,
    'latvia': StrategyAttributeCountryName.latvia,
    'lebanon': StrategyAttributeCountryName.lebanon,
    'lesotho': StrategyAttributeCountryName.lesotho,
    'liberia': StrategyAttributeCountryName.liberia,
    'libya': StrategyAttributeCountryName.libya,
    'liechtenstein': StrategyAttributeCountryName.liechtenstein,
    'lithuania': StrategyAttributeCountryName.lithuania,
    'luxembourg': StrategyAttributeCountryName.luxembourg,
    'madagascar': StrategyAttributeCountryName.madagascar,
    'malawi': StrategyAttributeCountryName.malawi,
    'malaysia': StrategyAttributeCountryName.malaysia,
    'maldives': StrategyAttributeCountryName.maldives,
    'mali': StrategyAttributeCountryName.mali,
    'malta': StrategyAttributeCountryName.malta,
    'marshall_islands': StrategyAttributeCountryName.marshallIslands,
    'mauritania': StrategyAttributeCountryName.mauritania,
    'mauritius': StrategyAttributeCountryName.mauritius,
    'mexico': StrategyAttributeCountryName.mexico,
    'micronesia_federated_states_of':
        StrategyAttributeCountryName.micronesiaFederatedStatesOf,
    'moldova': StrategyAttributeCountryName.moldova,
    'monaco': StrategyAttributeCountryName.monaco,
    'mongolia': StrategyAttributeCountryName.mongolia,
    'montenegro': StrategyAttributeCountryName.montenegro,
    'morocco': StrategyAttributeCountryName.morocco,
    'mozambique': StrategyAttributeCountryName.mozambique,
    'myanmar': StrategyAttributeCountryName.myanmar,
    'namibia': StrategyAttributeCountryName.namibia,
    'nauru': StrategyAttributeCountryName.nauru,
    'nepal': StrategyAttributeCountryName.nepal,
    'netherlands': StrategyAttributeCountryName.netherlands,
    'new_zealand': StrategyAttributeCountryName.newZealand,
    'nicaragua': StrategyAttributeCountryName.nicaragua,
    'niger': StrategyAttributeCountryName.niger,
    'nigeria': StrategyAttributeCountryName.nigeria,
    'north_macedonia': StrategyAttributeCountryName.northMacedonia,
    'norway': StrategyAttributeCountryName.norway,
    'oman': StrategyAttributeCountryName.oman,
    'pakistan': StrategyAttributeCountryName.pakistan,
    'palau': StrategyAttributeCountryName.palau,
    'panama': StrategyAttributeCountryName.panama,
    'papua_new_guinea': StrategyAttributeCountryName.papuaNewGuinea,
    'paraguay': StrategyAttributeCountryName.paraguay,
    'peru': StrategyAttributeCountryName.peru,
    'philippines': StrategyAttributeCountryName.philippines,
    'poland': StrategyAttributeCountryName.poland,
    'portugal': StrategyAttributeCountryName.portugal,
    'qatar': StrategyAttributeCountryName.qatar,
    'romania': StrategyAttributeCountryName.romania,
    'russia': StrategyAttributeCountryName.russia,
    'rwanda': StrategyAttributeCountryName.rwanda,
    'saint_kitts_and_nevis': StrategyAttributeCountryName.saintKittsAndNevis,
    'saint_lucia': StrategyAttributeCountryName.saintLucia,
    'saint_vincent_and_the_grenadines':
        StrategyAttributeCountryName.saintVincentAndTheGrenadines,
    'samoa': StrategyAttributeCountryName.samoa,
    'san_marino': StrategyAttributeCountryName.sanMarino,
    'sao_tome_and_principe': StrategyAttributeCountryName.saoTomeAndPrincipe,
    'saudi_arabia': StrategyAttributeCountryName.saudiArabia,
    'senegal': StrategyAttributeCountryName.senegal,
    'serbia': StrategyAttributeCountryName.serbia,
    'seychelles': StrategyAttributeCountryName.seychelles,
    'sierra_leone': StrategyAttributeCountryName.sierraLeone,
    'singapore': StrategyAttributeCountryName.singapore,
    'slovakia': StrategyAttributeCountryName.slovakia,
    'slovenia': StrategyAttributeCountryName.slovenia,
    'solomon_islands': StrategyAttributeCountryName.solomonIslands,
    'somalia': StrategyAttributeCountryName.somalia,
    'south_africa': StrategyAttributeCountryName.southAfrica,
    'spain': StrategyAttributeCountryName.spain,
    'sri_lanka': StrategyAttributeCountryName.sriLanka,
    'sudan': StrategyAttributeCountryName.sudan,
    'sudan_south': StrategyAttributeCountryName.sudanSouth,
    'suriname': StrategyAttributeCountryName.suriname,
    'sweden': StrategyAttributeCountryName.sweden,
    'switzerland': StrategyAttributeCountryName.switzerland,
    'syria': StrategyAttributeCountryName.syria,
    'taiwan': StrategyAttributeCountryName.taiwan,
    'tajikistan': StrategyAttributeCountryName.tajikistan,
    'tanzania': StrategyAttributeCountryName.tanzania,
    'thailand': StrategyAttributeCountryName.thailand,
    'togo': StrategyAttributeCountryName.togo,
    'tonga': StrategyAttributeCountryName.tonga,
    'trinidad_and_tobago': StrategyAttributeCountryName.trinidadAndTobago,
    'tunisia': StrategyAttributeCountryName.tunisia,
    'turkey': StrategyAttributeCountryName.turkey,
    'turkmenistan': StrategyAttributeCountryName.turkmenistan,
    'tuvalu': StrategyAttributeCountryName.tuvalu,
    'uganda': StrategyAttributeCountryName.uganda,
    'ukraine': StrategyAttributeCountryName.ukraine,
    'united_arab_emirates': StrategyAttributeCountryName.unitedArabEmirates,
    'united_kingdom': StrategyAttributeCountryName.unitedKingdom,
    'united_states': StrategyAttributeCountryName.unitedStates,
    'uruguay': StrategyAttributeCountryName.uruguay,
    'uzbekistan': StrategyAttributeCountryName.uzbekistan,
    'vanuatu': StrategyAttributeCountryName.vanuatu,
    'vatican_city': StrategyAttributeCountryName.vaticanCity,
    'venezuela': StrategyAttributeCountryName.venezuela,
    'vietnam': StrategyAttributeCountryName.vietnam,
    'yemen': StrategyAttributeCountryName.yemen,
    'zambia': StrategyAttributeCountryName.zambia,
    'zimbabwe': StrategyAttributeCountryName.zimbabwe
  };
  static Map<StrategyAttributeCountryName, String> toMap = {
    StrategyAttributeCountryName.afghanistan: 'afghanistan',
    StrategyAttributeCountryName.albania: 'albania',
    StrategyAttributeCountryName.algeria: 'algeria',
    StrategyAttributeCountryName.andorra: 'andorra',
    StrategyAttributeCountryName.angola: 'angola',
    StrategyAttributeCountryName.antiguaAndBarbuda: 'antigua_and_barbuda',
    StrategyAttributeCountryName.argentina: 'argentina',
    StrategyAttributeCountryName.armenia: 'armenia',
    StrategyAttributeCountryName.australia: 'australia',
    StrategyAttributeCountryName.austria: 'austria',
    StrategyAttributeCountryName.azerbaijan: 'azerbaijan',
    StrategyAttributeCountryName.theBahamas: 'the_bahamas',
    StrategyAttributeCountryName.bahrain: 'bahrain',
    StrategyAttributeCountryName.bangladesh: 'bangladesh',
    StrategyAttributeCountryName.barbados: 'barbados',
    StrategyAttributeCountryName.belarus: 'belarus',
    StrategyAttributeCountryName.belgium: 'belgium',
    StrategyAttributeCountryName.belize: 'belize',
    StrategyAttributeCountryName.benin: 'benin',
    StrategyAttributeCountryName.bhutan: 'bhutan',
    StrategyAttributeCountryName.bolivia: 'bolivia',
    StrategyAttributeCountryName.bosniaAndHerzegovina: 'bosnia_and_herzegovina',
    StrategyAttributeCountryName.botswana: 'botswana',
    StrategyAttributeCountryName.brazil: 'brazil',
    StrategyAttributeCountryName.brunei: 'brunei',
    StrategyAttributeCountryName.bulgaria: 'bulgaria',
    StrategyAttributeCountryName.burkinaFaso: 'burkina_faso',
    StrategyAttributeCountryName.burundi: 'burundi',
    StrategyAttributeCountryName.caboVerde: 'cabo_verde',
    StrategyAttributeCountryName.cambodia: 'cambodia',
    StrategyAttributeCountryName.cameroon: 'cameroon',
    StrategyAttributeCountryName.canada: 'canada',
    StrategyAttributeCountryName.centralAfricanRepublic:
        'central_african_republic',
    StrategyAttributeCountryName.chad: 'chad',
    StrategyAttributeCountryName.chile: 'chile',
    StrategyAttributeCountryName.china: 'china',
    StrategyAttributeCountryName.colombia: 'colombia',
    StrategyAttributeCountryName.comoros: 'comoros',
    StrategyAttributeCountryName.congoDemocraticRepublicOfThe:
        'congo_democratic_republic_of_the',
    StrategyAttributeCountryName.congoRepublicOfThe: 'congo_republic_of_the',
    StrategyAttributeCountryName.costaRica: 'costa_rica',
    StrategyAttributeCountryName.coteDivoire: 'cote_divoire',
    StrategyAttributeCountryName.croatia: 'croatia',
    StrategyAttributeCountryName.cuba: 'cuba',
    StrategyAttributeCountryName.cyprus: 'cyprus',
    StrategyAttributeCountryName.czechRepublic: 'czech_republic',
    StrategyAttributeCountryName.denmark: 'denmark',
    StrategyAttributeCountryName.djibouti: 'djibouti',
    StrategyAttributeCountryName.dominica: 'dominica',
    StrategyAttributeCountryName.dominicanRepublic: 'dominican_republic',
    StrategyAttributeCountryName.eastTimor: 'east_timor',
    StrategyAttributeCountryName.ecuador: 'ecuador',
    StrategyAttributeCountryName.egypt: 'egypt',
    StrategyAttributeCountryName.elSalvador: 'el_salvador',
    StrategyAttributeCountryName.equatorialGuinea: 'equatorial_guinea',
    StrategyAttributeCountryName.eritrea: 'eritrea',
    StrategyAttributeCountryName.estonia: 'estonia',
    StrategyAttributeCountryName.eswatini: 'eswatini',
    StrategyAttributeCountryName.ethiopia: 'ethiopia',
    StrategyAttributeCountryName.fiji: 'fiji',
    StrategyAttributeCountryName.finland: 'finland',
    StrategyAttributeCountryName.france: 'france',
    StrategyAttributeCountryName.gabon: 'gabon',
    StrategyAttributeCountryName.theGambia: 'the_gambia',
    StrategyAttributeCountryName.georgia: 'georgia',
    StrategyAttributeCountryName.germany: 'germany',
    StrategyAttributeCountryName.ghana: 'ghana',
    StrategyAttributeCountryName.greece: 'greece',
    StrategyAttributeCountryName.grenada: 'grenada',
    StrategyAttributeCountryName.guatemala: 'guatemala',
    StrategyAttributeCountryName.guinea: 'guinea',
    StrategyAttributeCountryName.guineaBissau: 'guinea_bissau',
    StrategyAttributeCountryName.guyana: 'guyana',
    StrategyAttributeCountryName.haiti: 'haiti',
    StrategyAttributeCountryName.honduras: 'honduras',
    StrategyAttributeCountryName.hungary: 'hungary',
    StrategyAttributeCountryName.iceland: 'iceland',
    StrategyAttributeCountryName.india: 'india',
    StrategyAttributeCountryName.indonesia: 'indonesia',
    StrategyAttributeCountryName.iran: 'iran',
    StrategyAttributeCountryName.iraq: 'iraq',
    StrategyAttributeCountryName.ireland: 'ireland',
    StrategyAttributeCountryName.israel: 'israel',
    StrategyAttributeCountryName.italy: 'italy',
    StrategyAttributeCountryName.jamaica: 'jamaica',
    StrategyAttributeCountryName.japan: 'japan',
    StrategyAttributeCountryName.jordan: 'jordan',
    StrategyAttributeCountryName.kazakhstan: 'kazakhstan',
    StrategyAttributeCountryName.kenya: 'kenya',
    StrategyAttributeCountryName.kiribati: 'kiribati',
    StrategyAttributeCountryName.koreaNorth: 'korea_north',
    StrategyAttributeCountryName.koreaSouth: 'korea_south',
    StrategyAttributeCountryName.kosovo: 'kosovo',
    StrategyAttributeCountryName.kuwait: 'kuwait',
    StrategyAttributeCountryName.kyrgyzstan: 'kyrgyzstan',
    StrategyAttributeCountryName.laos: 'laos',
    StrategyAttributeCountryName.latvia: 'latvia',
    StrategyAttributeCountryName.lebanon: 'lebanon',
    StrategyAttributeCountryName.lesotho: 'lesotho',
    StrategyAttributeCountryName.liberia: 'liberia',
    StrategyAttributeCountryName.libya: 'libya',
    StrategyAttributeCountryName.liechtenstein: 'liechtenstein',
    StrategyAttributeCountryName.lithuania: 'lithuania',
    StrategyAttributeCountryName.luxembourg: 'luxembourg',
    StrategyAttributeCountryName.madagascar: 'madagascar',
    StrategyAttributeCountryName.malawi: 'malawi',
    StrategyAttributeCountryName.malaysia: 'malaysia',
    StrategyAttributeCountryName.maldives: 'maldives',
    StrategyAttributeCountryName.mali: 'mali',
    StrategyAttributeCountryName.malta: 'malta',
    StrategyAttributeCountryName.marshallIslands: 'marshall_islands',
    StrategyAttributeCountryName.mauritania: 'mauritania',
    StrategyAttributeCountryName.mauritius: 'mauritius',
    StrategyAttributeCountryName.mexico: 'mexico',
    StrategyAttributeCountryName.micronesiaFederatedStatesOf:
        'micronesia_federated_states_of',
    StrategyAttributeCountryName.moldova: 'moldova',
    StrategyAttributeCountryName.monaco: 'monaco',
    StrategyAttributeCountryName.mongolia: 'mongolia',
    StrategyAttributeCountryName.montenegro: 'montenegro',
    StrategyAttributeCountryName.morocco: 'morocco',
    StrategyAttributeCountryName.mozambique: 'mozambique',
    StrategyAttributeCountryName.myanmar: 'myanmar',
    StrategyAttributeCountryName.namibia: 'namibia',
    StrategyAttributeCountryName.nauru: 'nauru',
    StrategyAttributeCountryName.nepal: 'nepal',
    StrategyAttributeCountryName.netherlands: 'netherlands',
    StrategyAttributeCountryName.newZealand: 'new_zealand',
    StrategyAttributeCountryName.nicaragua: 'nicaragua',
    StrategyAttributeCountryName.niger: 'niger',
    StrategyAttributeCountryName.nigeria: 'nigeria',
    StrategyAttributeCountryName.northMacedonia: 'north_macedonia',
    StrategyAttributeCountryName.norway: 'norway',
    StrategyAttributeCountryName.oman: 'oman',
    StrategyAttributeCountryName.pakistan: 'pakistan',
    StrategyAttributeCountryName.palau: 'palau',
    StrategyAttributeCountryName.panama: 'panama',
    StrategyAttributeCountryName.papuaNewGuinea: 'papua_new_guinea',
    StrategyAttributeCountryName.paraguay: 'paraguay',
    StrategyAttributeCountryName.peru: 'peru',
    StrategyAttributeCountryName.philippines: 'philippines',
    StrategyAttributeCountryName.poland: 'poland',
    StrategyAttributeCountryName.portugal: 'portugal',
    StrategyAttributeCountryName.qatar: 'qatar',
    StrategyAttributeCountryName.romania: 'romania',
    StrategyAttributeCountryName.russia: 'russia',
    StrategyAttributeCountryName.rwanda: 'rwanda',
    StrategyAttributeCountryName.saintKittsAndNevis: 'saint_kitts_and_nevis',
    StrategyAttributeCountryName.saintLucia: 'saint_lucia',
    StrategyAttributeCountryName.saintVincentAndTheGrenadines:
        'saint_vincent_and_the_grenadines',
    StrategyAttributeCountryName.samoa: 'samoa',
    StrategyAttributeCountryName.sanMarino: 'san_marino',
    StrategyAttributeCountryName.saoTomeAndPrincipe: 'sao_tome_and_principe',
    StrategyAttributeCountryName.saudiArabia: 'saudi_arabia',
    StrategyAttributeCountryName.senegal: 'senegal',
    StrategyAttributeCountryName.serbia: 'serbia',
    StrategyAttributeCountryName.seychelles: 'seychelles',
    StrategyAttributeCountryName.sierraLeone: 'sierra_leone',
    StrategyAttributeCountryName.singapore: 'singapore',
    StrategyAttributeCountryName.slovakia: 'slovakia',
    StrategyAttributeCountryName.slovenia: 'slovenia',
    StrategyAttributeCountryName.solomonIslands: 'solomon_islands',
    StrategyAttributeCountryName.somalia: 'somalia',
    StrategyAttributeCountryName.southAfrica: 'south_africa',
    StrategyAttributeCountryName.spain: 'spain',
    StrategyAttributeCountryName.sriLanka: 'sri_lanka',
    StrategyAttributeCountryName.sudan: 'sudan',
    StrategyAttributeCountryName.sudanSouth: 'sudan_south',
    StrategyAttributeCountryName.suriname: 'suriname',
    StrategyAttributeCountryName.sweden: 'sweden',
    StrategyAttributeCountryName.switzerland: 'switzerland',
    StrategyAttributeCountryName.syria: 'syria',
    StrategyAttributeCountryName.taiwan: 'taiwan',
    StrategyAttributeCountryName.tajikistan: 'tajikistan',
    StrategyAttributeCountryName.tanzania: 'tanzania',
    StrategyAttributeCountryName.thailand: 'thailand',
    StrategyAttributeCountryName.togo: 'togo',
    StrategyAttributeCountryName.tonga: 'tonga',
    StrategyAttributeCountryName.trinidadAndTobago: 'trinidad_and_tobago',
    StrategyAttributeCountryName.tunisia: 'tunisia',
    StrategyAttributeCountryName.turkey: 'turkey',
    StrategyAttributeCountryName.turkmenistan: 'turkmenistan',
    StrategyAttributeCountryName.tuvalu: 'tuvalu',
    StrategyAttributeCountryName.uganda: 'uganda',
    StrategyAttributeCountryName.ukraine: 'ukraine',
    StrategyAttributeCountryName.unitedArabEmirates: 'united_arab_emirates',
    StrategyAttributeCountryName.unitedKingdom: 'united_kingdom',
    StrategyAttributeCountryName.unitedStates: 'united_states',
    StrategyAttributeCountryName.uruguay: 'uruguay',
    StrategyAttributeCountryName.uzbekistan: 'uzbekistan',
    StrategyAttributeCountryName.vanuatu: 'vanuatu',
    StrategyAttributeCountryName.vaticanCity: 'vatican_city',
    StrategyAttributeCountryName.venezuela: 'venezuela',
    StrategyAttributeCountryName.vietnam: 'vietnam',
    StrategyAttributeCountryName.yemen: 'yemen',
    StrategyAttributeCountryName.zambia: 'zambia',
    StrategyAttributeCountryName.zimbabwe: 'zimbabwe'
  };

  static StrategyAttributeCountryName fromJson(dynamic data) =>
      data == null ? null : fromMap[data];

  dynamic toJson() => toMap[this];

  static List<StrategyAttributeCountryName> listFromJson(List<dynamic> json) =>
      json == null
          ? <StrategyAttributeCountryName>[]
          : json.map((value) => fromJson(value)).toList();

  static StrategyAttributeCountryName copyWith(
          StrategyAttributeCountryName instance) =>
      instance;

  static Map<String, StrategyAttributeCountryName> mapFromJson(
      Map<String, dynamic> json) {
    final map = <String, StrategyAttributeCountryName>{};
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) => map[key] = fromJson(value));
    }
    return map;
  }
}
