name: open_admin_app
description: FeatureHub Open Source Admin App front-end.


# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <=3.99.0'

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  dio: '^5.0.1'
  rxdart: ^0.27.0
  bloc_provider: ^0.8.0
  logging: ^1.0.1
  mrapi:
    path: ../app_mr_layer
  releases:
    path: ../releases_api
  openapi_dart_common: ^5.0.0
  zxcvbn: ^1.0.0
  universal_html: ^2.2.4
  url_launcher: ^6.3.2
  timeago: ^3.0.2
  shared_preferences: ^2.1.1
  flutter_signin_button: ^2.0.0
  advanced_datatable: ^0.0.9
  syncfusion_flutter_datagrid: ^21.2.10
  multiselect: ^0.1.1
  side_sheet: ^1.0.4+1
  async: ^2.9.0
  collection: ^1.17.1
  intl: ^0.20.2
  meta: ^1.8.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/logo/FeatureHub-icon.png
    - assets/logo/FeatureHubPrimaryWhite.png
    - assets/logo/FeatureHub-primary-navy.png
    - assets/logo/FlowerDarkBackground.png
    - assets/images/meditation.png

  fonts:
    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/SourceCodePro-Regular.ttf
        - asset: assets/fonts/SourceCodePro-Light.ttf
          weight: 300
    - family: FlutterIcon
      fonts:
        - asset: assets/fonts/FlutterIcon.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/MaterialIcons-Regular.ttf
    - family: NotoSansSymbols
      fonts:
        - asset: assets/fonts/NotoSansSymbols-Regular.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
