== Feature Hub Admin Web Application

=== Prerequisites
Flutter SDK

=== To run the app
Run from command line:

----
flutter channel master 

flutter update

cd $FLUTTER && git reset --hard f654346777603871f32cbf339c6652ef7b658ec0 && echo "1.22.0-10.0.pre.340" >> $FLUTTER/version

flutter config  --no-analytics --enable-web

flutter run -d chrome
----

Note: if you restart your IDE you should see the new device (Chrome)

To run/debug from in IDE setup a flutter run configuration point to main.dart

== Global error handling

There are 3 simple functions in the main Bloc for helping with errors:

`dialogError(e,s,{String messageTitle, bool showDetails = true,String messageBody=""})`

This will show a popup dialog with optional messageTitle and messageBody for custom messages in a Material Design Alert Dialog
You can optionally show exception and stacktrace details

It can be called in the following ways:

 justThrowError().catchError(bloc.mrClient.dialogError);

    try {
     throw (Exception("My exception"));}
     catch (e, s) {
        bloc.mrClient.dialogError(e, s);
    }

`void customError({String messageTitle="", String messageBody=""})`
Use when there is no exception or stacktrace, both parameters are optional

`consoleError(e,s)`
Use for insignificant errors that you want to only show in the browser console, not to the users

 justThrowError().catchError(bloc.mrClient.consoleError);

== Routing

The Open Admin front end uses a combination of an internal router and the Navigator 2 library from Flutter. There are
essentially two important states that we need to know about:

- does the backend exist at all? The MRBloc detects this by doing an initialization call and the route is `/loading` while this happens. 
  The valid responses are 200 (yes, initialized) or 404 (not initialized). 
- is the user logged in? This is surface in the PersonState which is accessed via the MR bloc. If the user has a valid token, the user
  is logged in, otherwise they are not.

For the Flutter Navigator - there is a central class - which for FH is called the `FHRouteDelegate`. It is responsible for:

- telling the browser what the URL should be given the internal state of the `FHRouteDelegate` - this is the method `currentConfiguration`
- listening to changes in the normal operation of the Admin application to change the route (e.g. via button clicks, or the left hand menu) and changing to that route
- listening to changes in the browser URL location (either by direct typing or forward/backward requests) and notifying the internal state to match. 

=== Data driven Routing Updates (internal changes)

We achieve this in the constructor of the `FHRouteDelegate` by listening to three streams from the MR Bloc: 

- is the app through its initialisation sequence? => `bloc.siteInitialisedSource` 
- the state of the person (are they logged in or not?) => `bloc.personState.personStream`
- has the app requested to change => `bloc.routeChangedStream`

When these things happen, these trigger the update of the internal state of the `FHRouteDelegate` - primarily indicating the route it should currently
be on. This route is represented by a class called `FHRoutePath` which currently stores data identical to the existing router functionality (name + params).

What does _trigger an update_ mean? It means calling `notifyListeners()` because `FHRouteDelegate` is a ChangeListener. This causes the `build` method to
be called and the widget tree to be updated. `FHRouteDelegate` is itself NOT a widget, even though it has a `build` method.

=== Browser driven Routing Updates (external changes)

If the browser link is updated instead (either via forward/backward or directly typing), then Flutter calls a different class to parse that information,
the `FHRouteInformationParser` will map a URL to a `FHRoutePath` and back again. If it takes a url from the browser, it will ask the 
`FHRoutePath` by calling ` `FHRouteInformationParser.parseRouteInformation` and then pass the corresponding object to the `FHRouteDelegate` from above
so it can update its internal state. It calls `notifyListeners` itself, so we don't need to do this.

The other part of this equation is when we go backwards or forwards, Flutter does something funky with _popping the page_ and there is some code that keeps
this all clean. It essentially copy-pasta from the docs. 

=== ToDOs

- There is no lifecycle on the `FHRouteDelegate` so we are unable to clean up the listeners as yet. We need to figure out some way to add it as if a user
changes the theme it will start having two+ firing state changes for the browser.
- Invalid URLs are not supported, they will just blow up I think?
[NO] - Should we include the portfolio + application in the url again? If so, should we consider removing the shared pref for it?
[YES] - the environment/service-account pages which are on tabs aren't "remembered"
- registration url isn't checked





