version: '3.1'

services:
  party-server:
    image: featurehub/party-server:0.0.6
    restart: always
    volumes:
      - ./app-config:/etc/app-config
    ports:
      - 8085:80
    depends_on:
      - "db"
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - featurehub-ps-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  featurehub-ps-db:
