openapi: 3.0.1
info:
  title: Enricher API
  description: This is an OpenAPI document for enriched data. It is used by Webhook
    Features directly.
  version: 1.2.0
servers:
- url: /
paths:
  /v2/fake:
    get:
      tags:
      - EnricherService
      description: "this is just a holder, it is not generated"
      operationId: fakeApi
      responses:
        "200":
          description: yay
components:
  schemas:
    EnrichedFeatures:
      required:
      - environment
      - featureKeys
      properties:
        targetEnrichmentDestination:
          type: string
          description: "If there is a specific target for the data, everything else\
            \ _should_ ignore it"
          nullable: true
        environment:
          $ref: '#/components/schemas/PublishEnvironment'
        featureKeys:
          type: array
          description: These are the keys of the features that were updated
          items:
            type: string
      description: A full environment with all of its features. This will filter out
        any management environmentInfo data
    PublishAction:
      type: string
      description: "Indicates what type of update this is. If CREATE, it is a new\
        \ record, if UPDATE it updates an existing one, if DELETE you should delete\
        \ the record. If EMPTY then it indicates there are no records of this type\
        \ and you shouldn't expect to see any further. EMPTY is used to indicate that\
        \ the Master process is complete."
      enum:
      - CREATE
      - UPDATE
      - DELETE
      - EMPTY
    PublishEnvironment:
      required:
      - action
      - environment
      - oId
      - pId
      - aId
      - fv
      - sa
      - c
      properties:
        environment:
          $ref: '#/components/schemas/CacheEnvironment'
        action:
          $ref: '#/components/schemas/PublishAction'
        oId:
          type: string
          description: organizationId
          format: uuid
        pId:
          type: string
          description: portfolioId
          format: uuid
        aId:
          type: string
          description: applicationId
          format: uuid
        fv:
          type: array
          description: featureValues
          items:
            $ref: '#/components/schemas/CacheEnvironmentFeature'
        sa:
          type: array
          description: serviceAccounts
          items:
            type: string
            format: UUID
        c:
          type: integer
          description: count
      description: Even a EMPTY message must set all the data to junk as it is an
        unusual situation
    CacheEnvironment:
      required:
      - id
      - version
      type: object
      properties:
        id:
          type: string
          format: uuid
        version:
          type: integer
          format: int64
        eInf:
          type: object
          additionalProperties:
            type: string
          description: (environmentInfo) - Allows extensibility for the environment
    CacheEnvironmentFeature:
      required:
      - feature
      type: object
      properties:
        feature:
          $ref: '#/components/schemas/CacheFeature'
        value:
          nullable: true
          allOf:
          - $ref: '#/components/schemas/CacheFeatureValue'
      description: A feature and its possible value
    CacheFeature:
      required:
      - id
      - key
      - valueType
      - version
      type: object
      properties:
        id:
          type: string
          format: uuid
        key:
          type: string
          description: Unique within this application
        valueType:
          $ref: '#/components/schemas/FeatureValueType'
        version:
          type: integer
          description: used for optimistic locking when renaming a feature
          format: int64
    FeatureValueType:
      type: string
      enum:
      - BOOLEAN
      - STRING
      - NUMBER
      - JSON
