= Developer SDK Documentation

So you want to write an SDK? That's awesome, thanks for joining the crew!


== What to know up front
There are a few things you need to know up front.

=== MIT License

All SDKs are MIT licensed. This is because they are included in the client's code base. That is generally as far 
as we can go, but try and choose dependencies that are MIT or similarly licensed. 

=== Server Sent Events

The key to the Feature Hub SDK is that all clients should receive updates at the same time. In the perfect world, this means
all of your stack updates instantly with your configured updates - backend and front-end. We ideally want to take
advantage of caching at CDN layers if we can.

To achieve this, there are only three technologies available across the major platforms that they have in common, plain
old HTTP, Server Sent Events, and Web Sockets. Lets brush HTTP/2 and HTTP/3 (QUIC) under the table for the time being. 

At its core, HTTP is a connectionless protocol, even with Keep-Alive, it is client driven protocol. As such, it isn't 
suitable for our stated goal of instantaneous updates. It is however important in our story, because it does allow
the user full control over when they update their features, and in a costly (both in real money data wise and in
battery life) environment, being able to have that control and yet still roll out features in a measured way is 
invaluable. We will use plain HTTP for our Mobile SDK when it comes along, and we use it for our test API to update
features.

WebSockets is essentially bi-directional tcp overlaid on the HTTP layer and it suffers a few problems for our use case.
It isn't cachable, it requires considerably greater complexity in terms of client implementation, and it is bi-directional,
which isn't really necessary in our case. WebSockets  have to regularly kill your connection to ensure that they don't
have stale phantom connections. 

That leaves us with one thing left, and given our kind of use case is exactly what it was designed for, it makes
sense that we use this technology. Server Sent Events came out in 2006 and is very widely supported in both the 
browser space (except for IE, which requires a polyfill) and through many client libraries. It is well supported by
web servers, and around the globe by all proxies and gateways. It doesn't require complex protocols like Socket.IO,
as it is a simple set of key values that periodically come down the wire. Further it is focused on server-push, is 
cachable, allowing you to use clever CDN's like https://www.fastly.com/blog/server-sent-events-fastly[Fastly]. 

SSE also kills your connection regularly to ensure stale connections are removed, but you can control that in 
FeatureHub and CDNs also used that as a key to refresh their own caches.

What is even better about SSE is that you can simply use `curl`, your normal browser inspection tools, and our
implementation of it is very easy to use and understand.

The downsides of it, as mentioned in that post by Fastly, are the same as with WebSockets. It keeps a radio link open
and so you shouldn't use it for Mobile without connecting and disconnecting. We intend to provide a simple GET API
for use in our Mobile APIs for Android (Java), iOS (Swift) and, of course, Dart for Flutter.

Back to HTTP/2 - this is a technology that we see best used from a CDN as it allows multiplexing multiple event streams
over one connection. HTTP/2 supports server sent events, but offers limited advantages unless more than just features
are being sourced from the same server.

Further information on SSE:

- https://en.wikipedia.org/wiki/Server-sent_events[Wikipedia]
- https://docs.servicestack.net/server-events[Service Stack]


=== OpenAPI

We use an OpenAPI definition for the SSE layer. Hold on you say, OpenAPI is a REST/JSON-RPC standard, it doesn't support
SSE. Yes, you would be right, it doesn't support WebSockets either. However, there is one REST call in the API, and
all of the data structures that are sent over the wire are listed in that document. It is merged from several files,
but essentially looks like this:

[source,yaml]
----
openapi: 3.0.1
info:
  title: FeatureServiceApi
  description: This describes the API clients use for accessing features
  version: "1.1.1"
paths:
  /features/{sdkUrl}/{featureKey}:
    put:
      tags:
        - FeatureService
      parameters:
        - name: sdkUrl
          in: path
          description: "The SDK key for the environment and service account"
          schema:
            type: string
        - name: featureKey
          in: path
          description: "The key you wish to update/action"
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FeatureStateUpdate"
      description: "Updates the feature state if allowed."
      operationId: setFeatureState
      responses:
        "200":
          description: update was accepted but not actioned because feature is already in that state
          content:
            application/json:
              schema:
                {}
        "201":
          description: update was accepted and actioned
          content:
            application/json:
              schema:
                {}
        "400":
          description: you have made a request that doesn't make sense. e.g. it has no data
          content:
            application/json:
              schema:
                {}
        "403":
          description: update was not accepted, attempted change is outside the permissions of this user
          content:
            application/json:
              schema:
                {}
        "404":
          description: something about the presented data isn't right and we couldn't find it, could be the service key, the environment or the feature
          content:
            application/json:
              schema:
                {}
        "412":
          description: you have made a request that isn't possible. e.g. changing a value without unlocking it.
          content:
            application/json:
              schema:
                {}

components:
  schemas:
    FeatureStateUpdate:
      type: object
      properties:
        value:
          description: "the new value"
        updateValue:
          type: boolean
          description: "indicates whether you are trying to update the value, as value can be null"
        lock:
          description: "set only if you wish to lock or unlock, otherwise null"
          type: boolean
    SSEResultState:
      type: string
      enum:
        - ack
        - bye
        - failure
        - features
        - feature
        - delete_feature
    FeatureState:
      required:
        - name
      properties:
        id:
          type: string
        key:
          type: string
        version:
          type: integer
          format: int64
        type:
          $ref: "#/components/schemas/FeatureValueType"
        value:
          description: "the current value"
        strategy:
          $ref: "#/components/schemas/Strategy"
    Strategy:
#      description: "This tells the client which strategy for roll out is being used".
      required:
        - name
      properties:
        name:
          $ref: "#/components/schemas/StrategyNameType"
        value:
          description: "this value is used if it is a simple attribute or percentage. If it is more complex then the pairs are passed"
        pairs:
          type: array
          items:
            $ref: "#/components/schemas/StrategyPair"
    StrategyNameType:
      type: string
      enum:
        - ATTRIBUTE
        - PERCENTAGE
    StrategyPair:
 #     description: "This is simply information the feature wishes to pass"
      required:
        - name
      properties:
        name:
          type: string
        value:
          type: string
    FeatureValueType:
      type: string
      enum:
        - BOOLEAN
        - STRING
        - NUMBER
        - JSON
    RoleType:
      type: string
      enum:
        - READ
        - LOCK
        - UNLOCK
        - CHANGE_VALUE


----

def credentialsValue
withCredentials(.....) {
  credentialsValue = env.SSH_something
}
echo $credentialsValue

You will notice the eventsource url is missing, and it is. If you use the standard 
https://github.com/OpenAPITools/openapi-generator[OpenAPI generator] as supported by the community, then you will
generally get a passable API. If you are having difficulty with it, please let us know - we have expertise in making
it work well.

== SDK submissions

From our perspective, we are happy to accept any contributions within our guidelines and that follow the basic requirements
of the SDK pattern we have established. It is fine that they are delivered in stages, we just ideally want to keep the
key functions the same between the different languages. 

It is worthwhile they be idiomatic to your language.

=== Before you start

We recommend you start up a FeatureHub Party Server docker image, and curl into the features - even use a browser for
your link and you will see a list of updates. The default server kicks you off every 30 seconds but that is configurable,
and is intended to ensure that you don't have stale, phantom connections.

If you create a feature, change a feature, delete a feature, add a new feature, all of these things you should be
able to watch and see come down the line. This is sort of what it should look like:

[source,http request]
----
curl -v http://localhost:8553/features/default/fc5b929b-8296-4920-91ef-6e5b58b499b9/VNftuX5LV6PoazPZsEEIBujM4OBqA1Iv9f9cBGho2LJylvxXMXKGxwD14xt2d7Ma3GHTsdsSO8DTvAYF
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8553 (#0)
> GET /features/default/fc5b929b-8296-4920-91ef-6e5b58b499b9/VNftuX5LV6PoazPZsEEIBujM4OBqA1Iv9f9cBGho2LJylvxXMXKGxwD14xt2d7Ma3GHTsdsSO8DTvAYF HTTP/1.1
> Host: localhost:8553
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: text/event-stream
< Transfer-Encoding: chunked
< 
event: ack
data: {"status":"discover"}

event: features
data: [{"id":"6c376de1-3cb8-4297-b641-8f27e0d11612","key":"FEATURE_SAMPLE","version":1,"type":"BOOLEAN","value":false},{"id":"b8d9b3a0-2972-4f56-a57f-3f74fe9c7e4f","key":"NEW_BUTTON","version":1,"type":"BOOLEAN","value":false},{"id":"5f562e19-aedf-44d5-ab5f-c2994e2b7f57","key":"NEW_BOAT","version":4,"type":"BOOLEAN","value":false}]

event: feature
data: {"id":"5f562e19-aedf-44d5-ab5f-c2994e2b7f57","key":"NEW_BOAT","version":5,"type":"BOOLEAN","value":true}

event: feature
data: {"id":"ae5e1af5-ac7d-475c-9862-7a3f88fa20d3","key":"dunk","type":"BOOLEAN"}

event: feature
data: {"id":"ae5e1af5-ac7d-475c-9862-7a3f88fa20d3","key":"dunk","version":1,"type":"BOOLEAN","value":false}

event: delete_feature
data: {"id":"ae5e1af5-ac7d-475c-9862-7a3f88fa20d3","key":"dunk","type":"BOOLEAN"}

event: bye
data: {"status":"closed"}

----

You can see it is a series of pairs: event, data. These are standard names in SSE, their values are what we control.

The event is the command, there is a special one called "error" that is managed by the protocol itself. But in our
case we are typically seeing:

- ack: i have received your request, I'm checking to see if everything is ok
- features: ok, this is the list of features and their current state

and then as things change

- feature - when a feature changes
- bye - when you are being kicked off

You would expect delete_feature to be rare.

=== Look at the other examples, talk to us

There are four other examples of the SDK so far, so have a look at their implementation. Chances are you have a 
passing familiarity with at least one of the languages. 

Please also talk to us, we are available on the #fh-sdk channel on the Anyways Labs Slack.

=== A Feature Repository

It is expected that there will be a repository pattern of some kind in each SDK. That may have all the functionality
pertaining to features, listeners, streamed updates, and analytics logging built in and yet actually do nothing itself.
The Java and Typescript versions are designed to distinctly separate the repository from the method used to feed
data into that repository - they are two separate artifacts. 

For the Java version, this has been done because Jersey is the first example stack, but there are many others in Java-land
and when we have a Mobile SDK, it will support Android-Java, which will not be able to use SSE. It also means if someone
built a pure NATs client or Kafka client, the same repository could be used. 

Consider approaching it this way, where the event source is passed the repository and it notifies that repository
as new events come in. 

However, if it is unlikely your repository will be used a different way, then merging them together makes sense. 

Typically, because the repository is what the main code base will interact with, a repository will be responsible for:

- holding all of the features
- keeping a track of the new features coming in and checking their versions to make sure they are new versions
- triggering events (callbacks, streams or whatever is idiomatic in your language) for when features change
- allowing clients to remove themselves from listening
- indicating the clients when the full list of features has arrived ("ready"). If your SSE layer actually blocks
until it has received the full list, this may be perfectly idiomatic, especially if your SDK is targeting servers or 
command line tools.
- analytics logging and registering senders
- other optional characteristics, such as the catch & release mode supported by Javascript and Dart (because of their
UI focus) 

=== The SSE Layer

This is normally a separate thing, and you would pass your repository into this and it would update it as new updates
come in. Exactly how this works is up to you, the Dart, Java and Typescript clients simply hand off the decoded event type
and the JSON blob and let the repository deal with the rest. 

The SSE layer could be held onto, it might not be. If for example you wanted to block until the full list of features
was available, you might hold onto this until it told you it was ready or it timed out. 

=== The Test Client

The Test API is something that an integration or e2e test would use to toggle features. Where it sits in your SDK is
up to you, it could simple be available by the generated OpenAPI client like it is in Dart. 

== Special thanks

To one of our contributors and the author of our Go SDK. https://github.com/chrusty[`@chrusty`] for prompting us for 
the need for this documentation.
