-- apply changes
create table fh_after_mig_job (
  id                            number(10) generated by default as identity not null,
  job_name                      varchar2(255) not null,
  completed                     number(1) default 0 not null,
  constraint pk_fh_after_mig_job primary key (id)
);

create table fh_fv_version (
  id                            varchar2(40) not null,
  version                       number(19) not null,
  fk_who_updated                varchar2(40),
  feature_state                 varchar2(8),
  default_value                 clob,
  locked                        number(1) default 0 not null,
  rollout_strat                 clob,
  retired                       number(1) default 0 not null,
  feature_id                    varchar2(40) not null,
  shared_strat                  clob,
  when_created                  timestamp not null,
  constraint ck_fh_fv_version_feature_state check ( feature_state in ('DISABLED','READY','ENABLED')),
  constraint pk_fh_fv_version primary key (id,version)
);

-- foreign keys and indices
create index ix_fh_fv_vrsn_fk_wh_pdtd on fh_fv_version (fk_who_updated);
alter table fh_fv_version add constraint fk_fh_fv_vrsn_fk_wh_pdtd foreign key (fk_who_updated) references fh_person (id) on delete set null;

create index ix_fh_fv_version_feature_id on fh_fv_version (feature_id);
alter table fh_fv_version add constraint fk_fh_fv_version_feature_id foreign key (feature_id) references fh_app_feature (id);

insert into fh_after_mig_job(id, completed, job_name) values (1, 0, 'upgrade-rollout-strategies');

