openapi: 3.0.1
info:
  title: Enricher API
  description: This is an OpenAPI document for enriched data. It is used by Webhook Features directly.
  version: "1.1.1"
paths:
  /v2/fake:
    get:
      operationId: fakeApi
      tags:
        - EnricherService
      description: "this is just a holder, it is not generated"
      responses:
        200:
          description: "yay"
components:
  schemas:
    EnrichedFeatures:
      x-cloudevent-type: enriched-feature-v1
      x-cloudevent-subject: io.featurehub.events.enricher
      x-package: io.featurehub.enriched.model
      description: "A full environment with all of its features. This will filter out any management environmentInfo data"
      required:
        - environment
        - featureKeys
      properties:
        targetEnrichmentDestination:
          description: "If there is a specific target for the data, everything else _should_ ignore it"
          type: string
        environment:
          $ref: "#/components/schemas/PublishEnvironment"
        featureKeys:
          description: "These are the keys of the features that were updated"
          type: array
          items:
            type: string

