openapi: 3.0.1
info:
  title: Internal Enricher API
  description: This is an OpenAPI document for enriched data. It is used by Webhook Features directly.
  version: "1.2.0"
paths:
  /v2/fake:
    get:
      operationId: fakeApi
      tags:
        - EnricherService
      description: "this is just a holder, it is not generated"
      responses:
        200:
          description: "yay"
components:
  schemas:
    EnricherPing:
      type: object
      x-cloudevent-type: enricher-ping-v1
      x-cloudevent-subject: io.featurehub.events.enricher
      x-package: io.featurehub.enriched.model
      required:
        - environment
        - cloudEventProcessor
      properties:
        environment:
          description: "The environment to extract from Dacha"
          type: string
          format: uuid
        cloudEventProcessor:
          description: "Include this field with the enriched features to indicate which client should be processing the request if a specific ping to determine if that client is working"
          type: string
