= Key concepts

== Portfolios

Portfolios are simply a collection of one or more applications.
Typically, portfolios are named to match areas of your business where groups of applications (or application suites) live.
Once created these portfolios can be managed by "Portfolio admins".
There is no limit to the number of portfolios you can have.

image::fh_overview.svg[Overview,500]

== Applications

Applications are where you create features and environments, they belong inside a portfolio.

== Environments

Applications have one or more environments, these typically refer to groups of co-operating deployments of your
application in different environments. There are often multiple development environments, testing environments,
acceptance testing and customer demo environments depending on the application.

When an application is created there is always an initial environment
called `Production` created. The values of your features are set, per environment.

Every FeatureHub environment has a unique ID, this ID plus a Service Account is what you reference in your application via the
SDK when you query for the value of the features.

== Features

Features are the main part of FeatureHub, they can be simple feature flags, strings, numbers or more advanced JSON
formats intended for forms of configuration.

=== Feature types

You can create features of the following types:

* `BOOLEAN` used for basic feature flags (toggles)
* `NUMBER` numerical values
* `STRING` string values
* `JSON` valid JSON only (typically used for remote configuration, or otherwise overriding internal values of an application)

NOTE: future support will exist for YAML and JSON-Schema to ensure valid configuration for JSON and YAML types.

=== Feature key

The feature key is the reference you use in your application, when you use the SDK,
you can check the value of a feature, referencing the feature key.
It *must be unique* for your application.

=== Feature value

When you add a feature flag, this will also automatically create a feature value in each environment. The default feature value will be set to `*off*` for `boolean` type and to `*null*` for `string`, `number` and `json`. By default, each feature value will be locked. Essentially feature value is always associated with an application and an environment for that application.

NOTE: See link:service-accounts{outfilesuffix}[Feature Permissions] for details on the various permission states a feature can have.

=== Deleting and retiring a feature

When feature flag is not needed any longer in your application, and you are ready to remove it, you can first "retire" this feature in a single environment to test how your application behaves, by setting it to the "Retired" state. This means that the feature won't be visible by the SDKs, imitating the "deleted" state. You can always "un-retire" a feature if you change your mind as this operation is reversible. Once you retire feature values across all the environments and test that your application behaves as expected, you can delete your entire feature. Deleting a feature means it is completely deleted from the system for all environments. This operation is not reversible. To retire a feature you will need environment specific "CHANGE_VALUE" permission. To delete a feature, you require an application specific permission to create, edit and delete features.
