openapi: 3.0.1
info:
  title: ManagementResourceApi
  description: This describes the API clients use for accessing features. This reflects the API from 1.6.1 onwards.
#  CRUD for portfolios, environments, features, service account, people, and groups (edited)
#  roles are fixed
#  then people<->group association
#  and group<->role association
paths:

  /mr-api/application/{id}/features:
    parameters:
      - name: id
        description: "The id of the application to find"
        in: path
        schema:
          type: string
          format: uuid
        required: true
      - name: includeMetaData
        description: "Include the metadata in the returned feature objects. Can be large."
        in: query
        schema:
          type: boolean
        required: false
      - name: includeArchived
        description: "Include archived/deleted features?"
        in: query
        required: false
        schema:
          type: boolean
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - FeatureService
      description: "get all features available in this application"
      operationId: getAllFeaturesForApplication
      responses:
        200:
          description: "Gets all features, alphabetically sorted"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Feature"
        400:
          description: "Bad Request"
        401:
          description: "no permission"
        403:
          description: "forbidden"
    post:
      security:
        - bearerAuth: [ ]
      tags:
        - FeatureService
      description: "add a new feature to this application, returns all features."
      operationId: createFeaturesForApplication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateFeature"
      responses:
        200:
          description: "All features, alphabetically sorted"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Feature"
        400:
          description: "Bad Request"
        401:
          description: "no permission"
        409:
          description: "Duplicate feature"
    put:
      parameters:
        - name: returnAllFeatures
          in: query
          schema:
            default: true
            type: boolean
          required: false
        - name: unarchiveFeature
          in: query
          description: "If this feature is archived and we want to update it, we have to pass this flag as true to restore it. This will fail if there is another feature of the same name already"
          required: false
          schema:
            default: false
            type: boolean
      security:
        - bearerAuth: [ ]
      tags:
        - FeatureService
      description: "updates all named features in this application, returns all features by default otherwise just the feature updated"
      operationId: updateFeatureForApplicationOnFeature
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Feature"
      responses:
        200:
          description: "All features, alphabetically sorted"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Feature"
        400:
          description: "Bad Request"
        401:
          description: "no permission"
        404:
          description: "not found"
        409:
          description: "duplicate feature"
        422:
          description: "other feature updated already"
  /mr-api/application/{id}/features/{key}:
    parameters:
      - name: id
        description: "The id of the application to find"
        in: path
        schema:
          type: string
          format: uuid
        required: true
      - name: key
        description: "The named unique key of the associated feature"
        in: path
        schema:
          type: string
        required: true
      - name: includeMetaData
        description: "Include the metadata in the returned feature objects. Can be large."
        in: query
        schema:
          type: boolean
        required: false
      - name: includeFilters
        description: "Include the filters associated with the flag"
        in: query
        required: false
        schema:
          type: boolean
      - name: includeArchived
        description: "Include archived/deleted features?"
        in: query
        required: false
        schema:
          type: boolean
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - FeatureService
      description: "get an individual feature"
      operationId: getFeatureByKey
      responses:
        200:
          description: "All features, alphabetically sorted"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Feature"
        400:
          description: "Bad Request"
        401:
          description: "no permission"
        404:
          description: "not found"
    put:
      security:
        - bearerAuth: [ ]
      tags:
        - FeatureService
      description: "updates all named features in this application, returns all features. Use this ONLY if you wish to change the key."
      operationId: updateFeatureForApplication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Feature"
      responses:
        200:
          description: "All features, alphabetically sorted"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Feature"
        400:
          description: "Bad Request"
        401:
          description: "no permission"
        404:
          description: "not found"
        409:
          description: "duplicate feature"
        422:
          description: "other feature updated already"
    delete:
      security:
        - bearerAuth: [ ]
      tags:
        - FeatureService
      description: "updates all named features in this application, returns all features."
      operationId: deleteFeatureForApplication
      responses:
        200:
          description: "All features, alphabetically sorted"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Feature"
        400:
          description: "Bad Request"
        401:
          description: "no permission"
        404:
          description: "none found"

  /mr-api/application/{id}/feature-environments/{key}:
    parameters:
      - name: id
        description: "The id of the application to find"
        in: path
        schema:
          type: string
          format: uuid
        required: true
      - name: key
        description: "The key of the associated feature"
        in: path
        schema:
          type: string
        required: true
      - name: includeArchived
        description: "Include archived/deleted features?"
        in: query
        required: false
        schema:
          type: boolean
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - FeatureService
      description: "Get a list of all environments and features and their values that this user has access to"
      operationId: getAllFeatureValuesByApplicationForKey
      responses:
        200:
          description: "Gets all feature values for all environments for an application"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FeatureEnvironment"
        400:
          description: "Bad Request"
        401:
          description: "no permission"
        404:
          description: "not found"
    put:
      security:
        - bearerAuth: [ ]
      tags:
        - FeatureService
      description: "Update a list of all environments and features and their values that this user has access to"
      operationId: updateAllFeatureValuesByApplicationForKey
      parameters:
        - name: removeValuesNotPassed
          description: "The id of the application to find"
          in: query
          schema:
            type: boolean
          required: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/FeatureValue"
      responses:
        200:
          description: "Gets all feature values for all environments for an application"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FeatureEnvironment"
        400:
          description: "Bad Request"
        401:
          description: "no permission"
        409:
          description: "Conflict in trying to save, someone else updated a record first"
        412:
          description: "The data being passed is invalid for some reason"
        422:
          description: "There were validation failures in the rollout strategies"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RolloutStrategyValidationResponse"
  /mr-api/application/{id}/all-feature-environment:
    parameters:
      - name: id
        description: "The id of the application to find"
        in: path
        schema:
          type: string
          format: uuid
        required: true
      - name: environmentIds
        description: "The environment ids to filter by. This should be limited to what the user is currently looking at or needing"
        in: query
        schema:
          type: array
          items:
            type: string
            format: uuid
      - name: filter
        description: "A filter to apply to the features - partial match of key or description"
        in: query
        schema:
          type: string
        required: false
      - name: max
        description: "The maximum number of features to get for this page"
        in: query
        schema:
          type: integer
        required: false
      - name: page
        description: "The page number of the results. 0 indexed."
        in: query
        schema:
          type: integer
        required: false
      - name: featureTypes
        in: query
        schema:
          type: array
          items:
            $ref: "#/components/schemas/FeatureValueType"
        required: false
      - name: sortOrder
        in: query
        schema:
          $ref: "#/components/schemas/SortOrder"
        required: false
      - name: featureFilter
        in: query
        description: "If specified, limit the feature list by those that have these filters associated"
        required: false
        schema:
          type: array
          items:
            type: string
            format: uuid
      - name: includeArchived
        description: "Include archived/deleted features?"
        in: query
        required: false
        schema:
          type: boolean
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - FeatureService
      description: "Get a list of all environments and features and their values that this user has access to"
      operationId: findAllFeatureAndFeatureValuesForEnvironmentsByApplication
      responses:
        200:
          description: "Gets all portfolios, alphabetically sorted"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationFeatureValues"
        400:
          description: "Bad Request"
        401:
          description: "no permission"
        404:
          description: "not found"
