openapi: 3.0.1
info:
  title: ManagementResourceApi
  description: This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
paths:
  /mr-api/portfolio/{id}/v2/group:
    parameters:
      - name: id
        description: "The id of the portfolio to find"
        in: path
        schema:
          type: string
          format: uuid
        required: true
      - name: includePeople
        description: "include people in each group"
        in: query
        schema:
          type: boolean
    put:
      security:
        - bearerAuth: [ ]
      tags:
        - GroupService
      description: "Update a group"
      operationId: updateGroupOnPortfolioV2
      parameters:
        - name: includeMembers
          description: "include people in each group"
          in: query
          required: false
          schema:
            type: boolean
        - name: includeMembersV2
          description: "include anemic people in each group with superuser"
          in: query
          required: false
          schema:
            type: boolean
        - name: includeGroupRoles
          description: "include environment and application roles in each group"
          in: query
          required: false
          schema:
            type: boolean
        - name: updateEnvironmentGroupRoles
          description: "update environment group roles, deleting any not passed"
          in: query
          schema:
            type: boolean
          required: false
        - name: updateApplicationGroupRoles
          description: "update application group roles, deleting any not passed"
          in: query
          schema:
            type: boolean
          required: false
        - name: applicationId
          description: "if updating the application group roles, and the application id is passed, then the changes are limited to that application"
          in: query
          schema:
            type: string
            format: uuid
          required: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateGroup"
      responses:
        200:
          description: "Resulting group"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Group"
        400:
          description: "Bad Request"
        401:
          description: "no permission"
        403:
          description: "forbidden"
        404:
          description: "not found"
        409:
          description: "duplicate user or duplicate group"
        422:
          description: "version conflict"
  /mr-api/portfolio/{id}/group:
    parameters:
      - name: id
        description: "The id of the portfolio to find"
        in: path
        schema:
          type: string
          format: uuid
        required: true
      - name: includePeople
        description: "include people in each group"
        in: query
        schema:
          type: boolean
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - GroupService
      description: "Gets a list of groups."
      operationId: findGroups
      parameters:
        - name: order
          in: query
          description: "how to order the results"
          schema:
            $ref: "#/components/schemas/SortOrder"
        - name: filter
          in: query
          description: "What to filter the results by"
          schema:
            type: string
      responses:
        200:
          description: "Gets groups, alphabetically sorted"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Group"
        400:
          description: "Bad Request"
        401:
          description: "no permission"
        403:
          description: "forbidden"
        404:
          description: "not found"
    post:
      security:
        - bearerAuth: [ ]
      tags:
        - GroupService
      description: "Create a new group"
      operationId: createGroup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateGroup"
      responses:
        200:
          description: "Resulting group"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Group"
        400:
          description: "Bad Request"
        401:
          description: "no permission"
        403:
          description: "no permission"
        409:
          description: "duplicate"
    put:
      security:
        - bearerAuth: [ ]
      tags:
        - GroupService
      description: "Update a group. Please use updateGroupOnPortfolioV2"
      deprecated: true
      operationId: updateGroupOnPortfolio
      x-removed-version: "1.12"
      parameters:
        - name: includeMembers
          description: "include people in each group"
          in: query
          schema:
            type: boolean
        - name: includeGroupRoles
          description: "include environment and application roles in each group"
          in: query
          schema:
            type: boolean
        - name: updateMembers
          description: "update members, deleting those that are not passed"
          in: query
          schema:
            type: boolean
          required: false
        - name: updateEnvironmentGroupRoles
          description: "update environment group roles, deleting any not passed"
          in: query
          schema:
            type: boolean
          required: false
        - name: updateApplicationGroupRoles
          description: "update application group roles, deleting any not passed"
          in: query
          schema:
            type: boolean
          required: false
        - name: applicationId
          description: "if updating the application group roles, and the application id is passed, then the changes are limited to that application"
          in: query
          schema:
            type: string
            format: uuid
          required: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Group"
      responses:
        200:
          description: "Resulting group"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Group"
        400:
          description: "Bad Request"
        401:
          description: "no permission"
        403:
          description: "forbidden"
        404:
          description: "not found"
        409:
          description: "duplicate user or duplicate group"
        422:
          description: "version conflict"

components:
  schemas:
    CreateGroup:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 255
        admin:
          nullable: true
          description: "is this an admin group?"
          type: boolean
        portfolioRoles:
          nullable: true
          uniqueItems: true
          type: array
          default: []
          items:
            $ref: "#/components/schemas/PortfolioGroupRoleType"
        applicationRoles:
          nullable: true
          type: array
          default: [ ]
          items:
            $ref: "#/components/schemas/ApplicationGroupRole"
    UpdateGroup:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          format: uuid
          nullable: false
        name:
          type: string
          maxLength: 255
          nullable: true
        version:
          type: integer
          format: int64
          nullable: false
        portfolioRoles:
          nullable: true
          type: array
          uniqueItems: true
          default: []
          items:
            $ref: "#/components/schemas/PortfolioGroupRoleType"
        applicationRoles:
          nullable: true
          type: array
          default: [ ]
          items:
            $ref: "#/components/schemas/ApplicationGroupRole"
        environmentRoles:
          type: array
          default: [ ]
          items:
            $ref: "#/components/schemas/EnvironmentGroupRole"
    Group:
      allOf:
        - $ref: "#/components/schemas/Audit"
        - type: object
          required:
            - name
            - id
          properties:
            id:
              type: string
              format: uuid
            admin:
              nullable: true
              description: "is this an admin group?"
              type: boolean
            portfolioId:
              nullable: true
              description: "The portfolio this group belongs to, unless it is the superuser group when it does not belong to one (null)"
              type: string
              format: uuid
            organizationId:
              nullable: true
              description: "this will be the organisation this group belongs to at the top level, or if a portfolio group, the organisation of the portfolio"
              type: string
              format: uuid
            version:
              type: integer
              format: int64
            name:
              type: string
              minLength: 1
              maxLength: 255
            superMembers:
              description: "This indicates which ids in the simpleMembers are superusers. It is a read only field and is ignored if it is passed back."
              type: array
              default: [ ]
              items:
                type: string
                format: uuid
            simpleMembers:
              type: array
              default: [ ]
              items:
                $ref: "#/components/schemas/AnemicPerson"
            members:
              type: array
              default: [ ]
              items:
                $ref: "#/components/schemas/Person"
            portfolioRoles:
              nullable: true
              type: array
              uniqueItems: true
              default: []
              items:
                $ref: "#/components/schemas/PortfolioGroupRoleType"
            applicationRoles:
              type: array
              default: [ ]
              items:
                $ref: "#/components/schemas/ApplicationGroupRole"
            environmentRoles:
              type: array
              default: [ ]
              items:
                $ref: "#/components/schemas/EnvironmentGroupRole"
            whenArchived:
              nullable: true
              type: string
              format: date-time
    GroupPerson:
      type: object
      properties:
        person:
          $ref: "#/components/schemas/AnemicPerson"
        superuser:
          type: boolean
    ApplicationGroupRole:
      type: object
      required:
        - applicationId
        - groupId
        - roles
      properties:
        applicationId:
          type: string
          format: uuid
        groupId:
          type: string
          format: uuid
        roles:
          type: array
          items:
            $ref: "#/components/schemas/ApplicationRoleType"
    PortfolioGroupRoleType:
      type: string
      description: "This is used to define new portfolio roles on this specific group. Anyone in this group now has these roles across the entire portfolio"
      enum:
        - GROUP_MEMBER_MANAGER  # someone who can edit members of groups across the portfolio but is not a portfolio manager
        - PORTFOLIO_STRATEGY_EDIT # someone who can edit portfolio strategies (create + edit)
        - PORTFOLIO_STRATEGY_EDIT_AND_DELETE # someone who can edit portfolio strategies and delete them
    ApplicationRoleType:
      type: string
      # FEATURE_EDIT is actually a CRUD role, people asked for the role to be separated into two
      # FEATURE_CREATE is CR - Create and Read
      # FEATURE_EDIT_AND_DELETE is RUD - FEATURE_CREATE + FEATURE_EDIT_AND_DELETE == FEATURE_EDIT
      # eventually FEATURE_EDIT will go away and this transition will start to occur in future versions
      enum:
        - FEATURE_EDIT
        - FEATURE_CREATE
        - FEATURE_EDIT_AND_DELETE
        - APP_STRATEGY_EDIT
        - APP_STRATEGY_CREATE
        - APP_STRATEGY_EDIT_AND_DELETE
    EnvironmentGroupRole:
      type: object
      required:
        - environmentId
        - groupId
        - roles
      properties:
        environmentId:
          type: string
          format: uuid
        groupId:
          type: string
          format: uuid
        roles:
          type: array
          items:
            $ref: "#/components/schemas/RoleType"
