openapi: 3.0.1
info:
  title: ManagementResourceApi
  description: This describes the API clients use for accessing features
paths:
  /mr-api/user-data/state/{appId}/hidden-environments:
    parameters:
      - name: appId
        in: path
        required: true
        schema:
          type: string
          format: uuid
    get:
      security:
        -  bearerAuth: []
      tags:
        - UserStateService
      description: "Gets information on which environments are hidden for this user"
      operationId: getHiddenEnvironments
      responses:
        "200":
          description: "the current set of hidden environments"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HiddenEnvironments"
        "401":
          description: "no permission to anything"
        "403":
          description: "no permission to environment"
        "404":
          description: "no such application"
        "422":
          description: "couldn't process request, something wrong"
    post:
      security:
        - bearerAuth: []
      tags:
        - UserStateService
      description: "Saves information on which environments should be hidden for this user"
      operationId: saveHiddenEnvironments
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/HiddenEnvironments"
      responses:
        "200":
          description: "the current set of hidden environments"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HiddenEnvironments"
        "401":
          description: "no permission to anything"
        "403":
          description: "no permission to environment"
        "404":
          description: "no such application"
        422:
          description: "update invalid, old"
components:
  schemas:
    HiddenEnvironments:
      type: object
      properties:
        noneSelected:
          type: boolean
          default: false
          description: "If this is set to true, then the user in fact has no selected environments"
        environmentIds:
          type: array
          items:
            type: string
            format: uuid
