/* 
 * FeatureServiceApi
 *
 * This describes the API clients use for accessing features
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IO.FeatureHub.SSE.Client.OpenAPIDateConverter;

namespace IO.FeatureHub.SSE.Model
{
    /// <summary>
    /// Defines StrategyNameType
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum StrategyNameType
    {
        /// <summary>
        /// Enum ATTRIBUTE for value: ATTRIBUTE
        /// </summary>
        [EnumMember(Value = "ATTRIBUTE")]
        ATTRIBUTE = 1,

        /// <summary>
        /// Enum PERCENTAGE for value: PERCENTAGE
        /// </summary>
        [EnumMember(Value = "PERCENTAGE")]
        PERCENTAGE = 2

    }

}
