name: app_singleapp
description: A new Flutter project.


# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.24.1
  bloc_provider: ^0.6.2
  logging: ^0.11.4
  mrapi:
    path: ../app_mr_layer
  openapi_dart_common: ^3.1.0
  xcvbnm: 1.0.0
  universal_html: ^1.2.3
  url_launcher: ^5.4.10
  intl: ^0.16.0
  timeago: ^2.0.26
  google_fonts: ^1.0.0
  # do not change this version of animator
  animator: 1.0.0+5
  shared_preferences: 0.5.6+3
  pedantic: ^1.9.0
  flutter_icons: ^1.1.0
  auto_size_text: 2.1.0
  collection: ^1.14.11

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/logo/FeatureHub-icon.png
    - assets/logo/FeatureHubPrimaryWhite.png
    - assets/logo/FlowerDarkBackground.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
