name: app_singleapp
description: A new Flutter project.


# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.26.0
  bloc_provider: ^0.8.0
  logging: ^1.0.1
  mrapi:
    path: ../app_mr_layer
  openapi_dart_common: ^4.0.0
  zxcvbn:
    git:
      url: https://github.com/lmordell/zxcvbn-dart.git
  universal_html: ^2.0.8
  url_launcher: ^6.0.3
  intl: ^0.17.0
  timeago: ^3.0.2
  google_fonts: ^2.0.0
  # do not change this version of animator
  animator: ^3.0.0
  shared_preferences: ^2.0.5
  plugin_platform_interface: ^2.0.0
  pedantic: ^1.11.0
  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons.git
      branch: null-safety-migration
  auto_size_text: ^3.0.0-nullsafety.0
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/logo/FeatureHub-icon.png
    - assets/logo/FeatureHubPrimaryWhite.png
    - assets/logo/FlowerDarkBackground.png
    - assets/signup_3rdparty/btn_google_signin_dark_normal_web.png
    - assets/signup_3rdparty/azure.png
    - assets/signup_3rdparty/github.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
