== Feature Hub Admin Web Application

=== Prerequisites
Flutter SDK

=== To run the app
Run from command line:

----
flutter channel master 

cd $FLUTTER && git reset --hard 54524a7f9559d56783a70cc8b87be95d42121460 && echo "1.19.0-2.0.pre.209" >> $FLUTTER/version

flutter config  --no-analytics --enable-web

flutter run -d chrome
----

Note: if you restart your IDE you should see the new device (Chrome)

To run/debug from in IDE setup a flutter run configuration point to main.dart

== Global error handling

There are 3 simple functions in the main Bloc for helping with errors:

`dialogError(e,s,{String messageTitle, bool showDetails = true,String messageBody=""})`

This will show a popup dialog with optional messageTitle and messageBody for custom messages in a Material Design Alert Dialog
You can optionally show exception and stacktrace details

It can be called in the following ways:

 justThrowError().catchError(bloc.mrClient.dialogError);

    try {
     throw (Exception("My exception"));}
     catch (e, s) {
        bloc.mrClient.dialogError(e, s);
    }

`void customError({String messageTitle="", String messageBody=""})`
Use when there is no exception or stacktrace, both parameters are optional

`consoleError(e,s)`
Use for insignificant errors that you want to only show in the browser console, not to the users

 justThrowError().catchError(bloc.mrClient.consoleError);


