The purpose of the SDK/ADK tests in this folder are to ensure that the more advanced use cases that are supported
by the FeatureHub SDK (such as strategies and attributes) are fully working as expected. 

What we are testing is the _flow_ - is data flowing properly from MR to Dacha to Edge - we are less interested in the 
behaviour of the SDK itself as that would require testing each SDK for the entire flow.

== Running in IDEA

Create a nodejs run config, this folder as the working directory, application
parameters should be `--require-module ts-node/register --require "app/**/*.ts"`
and Javascript file is `node_modules/.bin/cucumber-js`

== Setting up for the FeatureHub-Examples project

Running the `create-demo.sh` file will cause only those tests to run against the system that are necessary to
create the right features and then output the configuration necessary to stdout. These environment variables
can be copied into the appropriate run.sh files in the example directories.

== Running against a remote server

This assumes that SSE is enabled. 

Set `REMOTE_BEARER_TOKEN` to a Superuser level Admin level bearer token.

Set `REMOTE_BACKEND` to the https://X full location of your server.

if you want to test the webhook, use ngrok or similar and set the env var
EXTERNAL_NGROK and make sure it comes back to port 3000 e.g., `./ngrok 3000`

If you want to override the portfolio name when using ./create-demo.sh, use
`PORTFOLIO_NAME=pancakes ./create-demo.sh` (replace pancakes with whatever you
like, it needs to be unique for each run).

`WRITE_CONFIG` is used to allow writing the config generated by setting up the demo
example in a specific location. By default, it will drop into this folder.


