cache.name=default
maxSlots=60
server.gracePeriodInSeconds=1
jersey.cors.headers=X-Requested-With,Authorization,Content-type,Accept-Version,Content-MD5,CSRF-Token,x-ijt,cache-control,Baggage
jersey.logging.exclude-entirely-uris=/health/liveness,/health/readiness,/metrics
portfolio.admin.group.suffix=Administrators
monitor.port=8701
server.port=8553
