openapi: 3.0.1
info:
  title: Edge API Version 2
  description: This is the version 2 of the API for accessing features
  version: "1.1.1"
paths:
  /f2:
    get:
      tags:
        - FeatureV2Service
      parameters:
        - name: a
          in: query
          description: "A list of API keys to retrieve information about"
          required: true
          schema:
            type: array
            items:
              type: string
      description: Requests all features for this sdkurl and disconnects
      operationId: features
      responses:
        "200":
          description: feature request successful, all environments you have permission to or that were found are returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EdgeFeatureEnvironments"
        "236":
          description: its not you, its me, environment stagnant.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EdgeFeatureEnvironments"
        "400":
          description: you didn't ask for any environments
components:
  schemas:
    EdgeFieldPair:
      type: object
      additionalProperties:
        type: string
    SSEResponse:
      type: string
      x-publish-include: edge
      description: "error is an inherent state"
      enum:
        - ack
        - bye
        - failure
        - features
        - feature
        - delete_feature
        - config
        - error
    EdgeFeatureEnvironments:
      type: object
      properties:
        e:
          description: "Environments"
          x-longname: environments
          type: array
          items:
            $ref: "#/components/schemas/EdgeEnvironment"
    EdgeEnvironment:
      description: "This represents a collection of features as per a request from a GET api. GET's can request multiple API Keys at the same time."
      required:
        - id
        - f
      properties:
        id:
          type: string
        f:
          description: "features"
          x-longname: features
          nullable: false
          type: array
          items:
            $ref: "#/components/schemas/EdgeFeatureState"
    EdgeFeatureState:
      required:
        - k
        - id
        - v
      properties:
        id:
          type: string
          maxLength: 4
          description: first 4 characters of the ID, used to allow the key to change
        k:
          type: string
          x-longname: key
        l:
          x-longname: locked
          description: "Is this feature locked. Usually this doesn't matter because the value is the value, but for FeatureInterceptors it can matter. Defaults to no."
          type: integer
          default: 0
        v:
          x-longname: version
          description: "The version of the feature, this allows features to change values and it means we don't trigger events"
          type: integer
          format: int64
        t:
          $ref: "#/components/schemas/EdgeFeatureValueType"
        c:
          x-longname: value
          description: "the current value"
        si:
          description: "strategy id that was applied if this was a server evaluated feature"
          x-longname: strategyId
          type: string
        s:
          type: array
          nullable: true
          x-longname: strategies
          items:
            $ref: "#/components/schemas/EdgeRolloutStrategy"
    EdgeFeatureValueType:
      x-longname: type
      type: string
#      default: b
      x-enum-longname:
        b: BOOLEAN
        n: NUMBER
        j: JSON
        s: STRING
      enum:
        - b
        - n
        - j
        - s
    EdgeRolloutStrategy:
      description: "The model of the strategy from edge"
      required:
        - id
        - a
      properties:
        id:
          type: string
        a:
          x-longname: attributes
          type: array
          items:
            $ref: "#/components/schemas/EdgeFeatureRolloutStrategyAttribute"
        p:
          nullable: true
          x-longname: "percentage"
          description: "percentage: value between 0 and 1000000 - for four decimal places"
          type: integer
        pa:
          nullable: true
          x-longname: "percentageAttributes"
          type: array
          description: "if you don't wish to apply percentage based on user id, you can use one or more attributes defined here"
          items:
            type: string
        v:
          x-longname: value
          nullable: true
          description: "when we attach the RolloutStrategy for Dacha or SSE this lets us push the value out. Only visible in SDK and SSE Edge."
    EdgeFeatureRolloutStrategyAttribute:
      type: object
      required:
        - c
        - f
        - t
        - v
      properties:
        c:
          $ref: "#/components/schemas/EdgeAttributeConditional"
        f:
          x-longname: fieldName
          type: string
        vs:
          nullable: true
          x-longname: values
          description: "the value(s) associated with this rule (for matching)"
          type: array
          items:
            $ref: "#/components/schemas/EdgeRolloutStrategyArrayType"
        t:
          $ref: "#/components/schemas/EdgeRolloutStrategyFieldType"
        id:
          type: string
    EdgeRolloutStrategyArrayType:
      description: "values depend on the field type"
    EdgeRolloutStrategyFieldType:
      type: string
      x-longname: fieldType
      x-enum-longname:
        s: STRING
        sv: SEMANTIC_VERSION
        n: NUMBER
        d: DATE
        t: DATETIME
        b: BOOLEAN
        i: IP_ADDRESS
      enum:
        - s # STRING
        - sv # SEMANTIC_VERSION
        - n # NUMBER
        - d # DATE
        - t # DATETIME
        - b # BOOLEAN
        - i # IP_ADDRESS
    EdgeAttributeConditional:
      x-longname: conditional
      type: string
      x-enum-longname:
        e:  equals
        g:  greater
        ge: greater_equals
        l: less
        le: less_equals
        ne: not_equals
        ew: ends_with
        sw: starts_with
        i: includes
        x: excludes
        r: regex
      enum:
        - "e"  # equals
        - "g"  # greater
        - "ge" # greater equals
        - "l" # less
        - "le" # less equals
        - "ne" # not equals
        - "ew" # ends with
        - "sw" # starts with
        - "i" #includes
        - "x" #excludes
        - "r" #regex
    EdgeAttributeWellKnownNames:
      type: string
      x-enum-longname:
        d: device
        c: country
        p: platform
        u: userkey
        s: session
        v: version
      enum:
        - "d" # device
        - "c" # country
        - "p" # platform
        - "u" # userkey
        - "s" # session
        - "v" # version
    EdgeAttributeDeviceName:
      type: string
      x-enum-longname:
        b: browser
        m: mobile
        d: desktop
        s: server
        w: watch
        e: embedded
      enum:
        - "b" # browser
        - "m" # mobile
        - "d" # desktop
        - "s" # server
        - "w" # watch
        - "e" # embedded
    EdgeAttributePlatformName:
      type: string
      x-enum-longname:
        l: linux
        w: windows
        m: macos
        a: android
        i: ios
      enum:
        - "l" # linux
        - "w" # windows
        - "m" # macos
        - "a" # android
        - "i" # ios
    EdgeAttributeCountryName:
      x-publish-include: mr-api,edge
      type: string
      description: "https://www.britannica.com/topic/list-of-countries-1993160 - we put these in API so everyone can have the same list"
      x-enum-longname:
        af: afghanistan
        al: albania
        dz: algeria
        ad: andorra
        ao: angola
        ag: antigua_and_barbuda
        ar: argentina
        am: armenia
        au: australia
        at: austria
        az: azerbaijan
        bs: the_bahamas
        bh: bahrain
        bd: bangladesh
        bb: barbados
        by: belarus
        be: belgium
        bz: belize
        bj: benin
        bt: bhutan
        bo: bolivia
        ba: bosnia_and_herzegovina
        bw: botswana
        br: brazil
        bn: brunei
        bg: bulgaria
        bf: burkina_faso
        bi: burundi
        cv: cabo_verde
        kh: cambodia
        cm: cameroon
        ca: canada
        cf: central_african_republic
        td: chad
        cl: chile
        cn: china
        co: colombia
        km: comoros
        cd: congo_democratic_republic_of_the
        cg: congo_republic_of_the
        cr: costa_rica
        ci: cote_divoire
        hr: croatia
        cu: cuba
        cy: cyprus
        cz: czech_republic
        dk: denmark
        dj: djibouti
        dm: dominica
        do: dominican_republic
        tl: east_timor
        ec: ecuador
        eg: egypt
        sv: el_salvador
        gq: equatorial_guinea
        er: eritrea
        ee: estonia
        sz: eswatini
        et: ethiopia
        fj: fiji
        fi: finland
        fr: france
        ga: gabon
        gm: the_gambia
        ge: georgia
        de: germany
        gh: ghana
        gr: greece
        gd: grenada
        gt: guatemala
        gn: guinea
        gw: guinea_bissau
        gy: guyana
        ht: haiti
        hn: honduras
        hu: hungary
        is: iceland
        in: india
        id: indonesia
        ir: iran
        iq: iraq
        ie: ireland
        il: israel
        it: italy
        jm: jamaica
        jp: japan
        jo: jordan
        kz: kazakhstan
        ke: kenya
        ki: kiribati
        kp: korea_north
        kr: korea_south
        xk: kosovo
        kw: kuwait
        kg: kyrgyzstan
        la: laos
        lv: latvia
        lb: lebanon
        ls: lesotho
        lr: liberia
        ly: libya
        li: liechtenstein
        lt: lithuania
        lu: luxembourg
        mg: madagascar
        mw: malawi
        my: malaysia
        mv: maldives
        ml: mali
        mt: malta
        mh: marshall_islands
        mr: mauritania
        mu: mauritius
        mx: mexico
        fm: micronesia_federated_states_of
        md: moldova
        mc: monaco
        mn: mongolia
        me: montenegro
        ma: morocco
        mz: mozambique
        mm: myanmar
        na: namibia
        nr: nauru
        np: nepal
        nl: netherlands
        nz: new_zealand
        ni: nicaragua
        ne: niger
        ng: nigeria
        mk: north_macedonia
        no: norway
        om: oman
        pk: pakistan
        pw: palau
        pa: panama
        pg: papua_new_guinea
        py: paraguay
        pe: peru
        ph: philippines
        pl: poland
        pt: portugal
        qa: qatar
        ro: romania
        ru: russia
        rw: rwanda
        kn: saint_kitts_and_nevis
        lc: saint_lucia
        vc: saint_vincent_and_the_grenadines
        ws: samoa
        sm: san_marino
        st: sao_tome_and_principe
        sa: saudi_arabia
        sn: senegal
        rs: serbia
        sc: seychelles
        sl: sierra_leone
        sg: singapore
        sk: slovakia
        si: slovenia
        sb: solomon_islands
        so: somalia
        za: south_africa
        es: spain
        lk: sri_lanka
        sd: sudan
        ss: sudan_south
        sr: suriname
        se: sweden
        ch: switzerland
        sy: syria
        tw: taiwan
        tj: tajikistan
        tz: tanzania
        th: thailand
        tg: togo
        to: tonga
        tt: trinidad_and_tobago
        tn: tunisia
        tr: turkey
        tm: turkmenistan
        tv: tuvalu
        ug: uganda
        ua: ukraine
        ae: united_arab_emirates
        uk: united_kingdom
        us: united_states
        uy: uruguay
        uz: uzbekistan
        vu: vanuatu
        va: vatican_city
        ve: venezuela
        vn: vietnam
        ye: yemen
        zm: zambia
        zw: zimbabwe
      enum:
        - af # afghanistan
        - al # albania
        - dz # algeria
        - ad # andorra
        - ao # angola
        - ag # antigua_and_barbuda
        - ar # argentina
        - am # armenia
        - au # australia
        - at # austria
        - az # azerbaijan
        - bs # the_bahamas
        - bh # bahrain
        - bd # bangladesh
        - bb # barbados
        - by # belarus
        - be # belgium
        - bz # belize
        - bj # benin
        - bt # bhutan
        - bo # bolivia
        - ba # bosnia_and_herzegovina
        - bw # botswana
        - br # brazil
        - bn # brunei
        - bg # bulgaria
        - bf # burkina_faso
        - bi # burundi
        - cv # cabo_verde
        - kh # cambodia
        - cm # cameroon
        - ca # canada
        - cf # central_african_republic
        - td # chad
        - cl # chile
        - cn # china
        - co # colombia
        - km # comoros
        - cd # congo_democratic_republic_of_the
        - cg # congo_republic_of_the
        - cr # costa_rica
        - ci # cote_divoire
        - hr # croatia
        - cu # cuba
        - cy # cyprus
        - cz # czech_republic
        - dk # denmark
        - dj # djibouti
        - dm # dominica
        - do # dominican_republic
        - tl # east_timor
        - ec # ecuador
        - eg # egypt
        - sv # el_salvador
        - gq # equatorial_guinea
        - er # eritrea
        - ee # estonia
        - sz # eswatini
        - et # ethiopia
        - fj # fiji
        - fi # finland
        - fr # france
        - ga # gabon
        - gm # the_gambia
        - ge # georgia
        - de # germany
        - gh # ghana
        - gr # greece
        - gd # grenada
        - gt # guatemala
        - gn # guinea
        - gw # guinea_bissau
        - gy # guyana
        - ht # haiti
        - hn # honduras
        - hu # hungary
        - is # iceland
        - in # india
        - id # indonesia
        - ir # iran
        - iq # iraq
        - ie # ireland
        - il # israel
        - it # italy
        - jm # jamaica
        - jp # japan
        - jo # jordan
        - kz # kazakhstan
        - ke # kenya
        - ki # kiribati
        - kp # korea_north
        - kr # korea_south
        - xk # kosovo
        - kw # kuwait
        - kg # kyrgyzstan
        - la # laos
        - lv # latvia
        - lb # lebanon
        - ls # lesotho
        - lr # liberia
        - ly # libya
        - li # liechtenstein
        - lt # lithuania
        - lu # luxembourg
        - mg # madagascar
        - mw # malawi
        - my # malaysia
        - mv # maldives
        - ml # mali
        - mt # malta
        - mh # marshall_islands
        - mr # mauritania
        - mu # mauritius
        - mx # mexico
        - fm # micronesia_federated_states_of
        - md # moldova
        - mc # monaco
        - mn # mongolia
        - me # montenegro
        - ma # morocco
        - mz # mozambique
        - mm # myanmar
        - na # namibia
        - nr # nauru
        - np # nepal
        - nl # netherlands
        - nz # new_zealand
        - ni # nicaragua
        - ne # niger
        - ng # nigeria
        - mk # north_macedonia
        - no # norway
        - om # oman
        - pk # pakistan
        - pw # palau
        - pa # panama
        - pg # papua_new_guinea
        - py # paraguay
        - pe # peru
        - ph # philippines
        - pl # poland
        - pt # portugal
        - qa # qatar
        - ro # romania
        - ru # russia
        - rw # rwanda
        - kn # saint_kitts_and_nevis
        - lc # saint_lucia
        - vc # saint_vincent_and_the_grenadines
        - ws # samoa
        - sm # san_marino
        - st # sao_tome_and_principe
        - sa # saudi_arabia
        - sn # senegal
        - rs # serbia
        - sc # seychelles
        - sl # sierra_leone
        - sg # singapore
        - sk # slovakia
        - si # slovenia
        - sb # solomon_islands
        - so # somalia
        - za # south_africa
        - es # spain
        - lk # sri_lanka
        - sd # sudan
        - ss # sudan_south
        - sr # suriname
        - se # sweden
        - ch # switzerland
        - sy # syria
        - tw # taiwan
        - tj # tajikistan
        - tz # tanzania
        - th # thailand
        - tg # togo
        - to # tonga
        - tt # trinidad_and_tobago
        - tn # tunisia
        - tr # turkey
        - tm # turkmenistan
        - tv # tuvalu
        - ug # uganda
        - ua # ukraine
        - ae # united_arab_emirates
        - uk # united_kingdom
        - us # united_states
        - uy # uruguay
        - uz # uzbekistan
        - vu # vanuatu
        - va # vatican_city
        - ve # venezuela
        - vn # vietnam
        - ye # yemen
        - zm # zambia
        - zw # zimbabwe

