== Description
Frontend Todo app to demonstrate the usage of FeatureHub Javascript/Typescript SDK with React front-end framework.


Demonstrates the feature of "STRING" type that controls the colour of a "SUBMIT" button. For example, you can set it as "green", "orange" etc..

In addition, it demonstrates integration with Google Analytics. You will require to have valid GA Tracking ID, e.g. 'UA-XXXXXXXXX-X',
and so  the code is currently commented out.

=== Configuration

The application requires a host which will be the backend and also an SDK URL before it can properly function. Once
you have these, you need to specify them in the `public/featurehub-config.json` file and the application will load
them. This is not particularly a recommended practice, it is simply easy for us to use when running in a docker
environment rather than having to search/replace in a large js file.

Requirements:

* Feature key: `SUBMIT_COLOR_BUTTON` - this can be configured after you create the Application and Environment to 
demonstrate that the application will listen even when the feature does not exist.
* SDK URL, fully resolved depending on where you are running the SSE Edge Server
* Backend URL (which must be CORS enabled, both the Java and Typescript ones are) full resolved.

If you also want GA-events, you need to have:

* GA-ID - in the form of UA-XXXXX. We specify a random CID as we have no user data, it does not matter.

GA events:

`name: "todo-add", value: "10"`

`name: "todo-delete", value: "5"`

Once you launch the app, any interaction with "add" or "delete" buttons will generate a GA event accordingly. 

Note: The events will appear in your GA console with ~12 hours delay.

More on GA integration can be found here https://docs.featurehub.io/#_google_analytics_integration


== Prerequisites 
Node @12 or higher  

Follow readme instructions to build  `client-typescript-core` module

Follow readme instructions to build  `client-typescript-eventsource` module

== Installation Instructions

Install dependencies

`npm install`

Generate AXIOS openapi client

`mvn clean generate-sources`

Link to local versions of feature-hub repositories

`npm run-script local-link`

Run back-end server: 

`cd ./todo-backend-typescript` 

`npm install && npm run-script start`

After back-end server has started successfully:

`cd ./todo-frontend-react-typescript`

`npm run-script compile`

`npm run-script start`





