"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * FeatureServiceApi
 * This describes the API clients use for accessing features
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Environment = void 0;
/**
*
* @export
* @class Environment
*/
class Environment {
    constructor(init) {
        Object.assign(this, init);
    }
}
exports.Environment = Environment;
//# sourceMappingURL=environment.js.map