/* tslint:disable */
/* eslint-disable */
/**
 * FeatureServiceApi
 * This describes the API clients use for accessing features
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { FeatureState } from './feature-state';

  /**
* 
* @export
* @class Environment
*/
export class Environment {
  /**
  * 
  * @type {string}
  * @memberof Environment
  */
  public id?: string;
  /**
  * 
  * @type {Array<FeatureState>}
  * @memberof Environment
  */
  public features?: Array<FeatureState>;

  constructor(init?: Partial<Environment>) {
    Object.assign(this, init);
  }
}


