"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * FeatureServiceApi
 * This describes the API clients use for accessing features
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RoleType = void 0;
/**
*
* @export
* @enum {string}
*/
var RoleType;
(function (RoleType) {
    RoleType["Read"] = "READ";
    RoleType["Lock"] = "LOCK";
    RoleType["Unlock"] = "UNLOCK";
    RoleType["ChangeValue"] = "CHANGE_VALUE";
})(RoleType = exports.RoleType || (exports.RoleType = {}));
//# sourceMappingURL=role-type.js.map