"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * FeatureServiceApi
 * This describes the API clients use for accessing features
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SSEResultState = void 0;
/**
*
* @export
* @enum {string}
*/
var SSEResultState;
(function (SSEResultState) {
    SSEResultState["Ack"] = "ack";
    SSEResultState["Bye"] = "bye";
    SSEResultState["Failure"] = "failure";
    SSEResultState["Features"] = "features";
    SSEResultState["Feature"] = "feature";
    SSEResultState["DeleteFeature"] = "delete_feature";
})(SSEResultState = exports.SSEResultState || (exports.SSEResultState = {}));
//# sourceMappingURL=sseresult-state.js.map