==== Event Streaming

This relates to the primary purpose of the FeatureHub platform, which is a platform by which a client is able to connect and then receive a constant stream of real-time updates to the features as they change.
This mechanism is supported via Server Side Events.

==== Background Start

This relates to the ability for the application to connect to a FeatureHub Edge server in the background and complete the initial transactions and continue listening for updates - all in the background.

==== Block until Start

This is usually a capability provided instead of readyness listeners, whereby the library can be told to wait until the connection has been successfully established and there is a list of features, or the connection fails for some reason.
It is used to ensure a client has a consistent set of features before functioning and is generally best used for server side software.

==== Readyness Listeners

These perform a similar function to Block until Start, but instead a server can call back or query the readyness status directly and perform the blocking function themselves.
The ToDo Java and Typescript examples use this mechanism.

==== Feature Listeners

This allows client code to listen for changes in the state of a feature, and to trigger some action based on the new state.
Generally the whole feature is passed to the listener for it to interrogate.

==== Feature Listener Removal

Some clients like to, or need to (usually UI related) remove listeners they have created.
This allows them to do that.

==== Analytics Support

This is where the library has a mechanism to log an event, potentially attach metadata.
The library captures the state of all of the features at the point in time of the request and will pass it on to any registered Analytics provider.
A platform can have analytics support but no analytics providers.
We intend over time to support only one, where the data is posted to a backend service which you can then decide where to send and how to send the data.

==== Google Analytics

This is a client side implementation of the Analytics support.
It is designed so you need to specify the `User-ID` or `CID`, your `UA-` id and when logging an event, it will fire off into GA the event - one for each value of non-JSON features.

=== Web + Mobile Capabilities

The following capabilities are focused on clients that provide a UI to the client and thus you may wish to control
the updating of the features.

==== Catch & Release

Some clients don't want the feature updates to be immediately triggered in real-time.
These are usually those that use Feature Listeners and they want to hold onto the changes until they have informed the user there are changes - via some UI element (e.g. reload for new functionality).
Catch and release mode normally includes a flag to set it, an extra callback to indicate new features have come in, and then a release method to indicate the new features should be released (their state changed and the listeners triggered).
The Typescript, Javascript and Dart libraries all have examples of this.

If you use catch and release, it is worthwhile considering enabling OpenTracing feature overrides in production.
You can configure feature interceptors to not be allowed to override locked features.

=== Client and server SDKs //todo

=== Test automation support 

Test Client / Feature Updater is designed to allow tests to change the values of features in their environments while they are running.

This will depend on the permissions granted to the service account in the environment that is configured.

Besides READ permission, a typical service account would need UNLOCK and CHANGE_VALUE to allow tests to modify values.
Alternatively if features are always unlocked in test environments (which is often the case), CHANGE_VALUE is all that is required, and READ is implicit.

Changes are checked against the latest version of the feature in the cache.
Changes that match the current state are simply ignored (and a 200 response given).
Changes generally take a second or two to propagate.

For other cases, the `FeatureStateUpdate` class has three fields.

- `lock` - if passed it will change the state of the lock.
You need LOCK permission to lock, UNLOCK permission to unlock.
If a feature is locked, any attempt to change it will be ignored.
- `value` - this is an "object" because it represents all types of values supported.
It can be null.
If it is null, and you want to ensure this is set to null (which is ignored for feature flags), make sure you set `updateValue`.
- `updateValue` - this is specifically for the situation where you are setting a non feature flag to have a null value.
Otherwise passing a value will assume this is true.

=== Feature Interceptors

Feature Interceptors are the ability to intercept the request for a feature. They only operate in imperative state, so when
code specifically requests the value of a feature, they don't cause events to trigger. They are designed to function
to enable specific kinds of use cases, such as:

- allowing external storage of features, such as in a text file. This allows developers to override the value of features in their local running infrastructure without having to have a dedicated Environment for themselves or be connected.
- allow per request overriding of features for example with OpenTracing or OpenTelemetry.
Because of the nature of OpenTracing and OpenTelemetry, this allows you to listen to events from message queue systems like NATs, Kafka, ActiveMQ, etc.

It is unlikely you would be using these in production or staging environments as they are designed to make the development and testing of your feature based applications easier.
They can however be used in production, and you can tell them that if the feature is locked, their statuses cannot be overridden.
So in a test or development environment you should unlock your features and other environments you should lock them.

This prevents bad actors from poking at your apis and turning features on before they are ready.

=== Licensing

All SDKs are MIT licensed, as they reside in the client codebase.
Downstream dependencies are not assured to be so.
