= Installation of FeatureHub
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:toc: left
:toclevels: 4
:toc-title: Contents

link:index{outfilesuffix}[Back to index]

== Overview
There are 3 main deployment options for running FeatureHub. As FeatureHub is packaged as a _Cloud Native_
bundle, all parts are Docker images and are intended to be used with that technology (i.e. Docker or Kubernetes).

All sample configurations are in the `run-configurations` folder. All of the run configurations mount the
database volume separately from the main set of containers, allowing you to upgrade your database and
versions of FeatureHub without destroying your database.

NOTE: FeatureHub runs on the following SQL Databases: PostgreSQL, MySQL, MS SQL Server, Oracle and we provide
initialization and migration DDL for each of these databases. Others can be supported, please contact us.

== Starting small

If you wish to get up and running without using `docker-compose` and downloading this repository, we would
recommend running this simple line:

----
docker run -p 8085:8085 -v ~/tmp:/db featurehub/party-server:0.0.4
----

where `~/tmp` is where you wish to store the database. This will start FeatureHub on port 8085 and you can now
create your first Superuser, Portfolio, Application, Feature etc.

Once you have done this, you can then simply run the example project and tie the two together.

== Running the example

The example will need to know the SDK URL of your environment, and it will need an IP address that the second
docker can get access to. If you know how to use docker networks, you should be able to find this easily, otherwise
find your en0 ip address (you can type: `ifconfig en0` - choose the inet address, Windows will be slightly different)
or similar, do not use localhost as that will not work.

----
export SDK_URL=default/d8ba747d-7d3c-4454-9c58-130390848412/5EE3vua1NqY0ez6Zd4TXU7XnsZdAPHtR96XaDmhfegitKGiQ9aCdmtmeNUNPubkRZLJLUUpaC7b05ELk
export MY_IP=192.168.XX.XX
docker run -e FEATUREHUB_APP_ENV_URL=http://$MY_IP:8085/features/$SDK_URL -p 5000:5000  featurehub/example_node:0.0.1
----

This will cause the example to start and you can access it on port 5000. Add a few todo's in mixed case.
If you create a feature flag called `FEATURE_TITLE_TO_UPPERCASE`, unlock it and set it to true, you will see a "refresh"
message appear. If you refresh, it will upper case everything, experiment. This flag is affecting the backend.

If you create a feature value - a String value called `SUBMIT_COLOR_BUTTON` and set its value to (say) `cyan`, you will
again see a refresh indicator and on refresh the Add button will swap to Cyan. Each time you change the colour, it will
recommend you refresh. It is doing this because it is set in "catch and release" mode, and we recommend you read up on
the SDKs for further information on this.

== Deployment options

=== Option 1 - Evaluation Deployment
This is the most basic option recommended for getting started quickly, and is the example we use in demos.

It uses one Docker container for the entire stack and works with all supported databases
baked in. The two web endpoints of interest -  the Management Server and the Edge layer that client
SDKs talk to - are all served from the same web server .

This deployment, with an attached Docker volume for the database, is not recommended for production usage,
it is only really for demonstration and evaluation purposes.

We provide two evaluation examples - one for H2 and one for Postgres, the configurations for these are
`run-configurations/all-in-one-h2` and `run-configurations/all-in-one-postgres` respectively.

image::images/fh_deployment_option_1.svg[Option 1,500]

NOTE: H2 and Postgres are the two databases we test actively with.

=== Option 2 - Low Volume Deployment
In this deployment, all components (MR, Dacha, NATS, Edge) are split into separate Docker containers, but
`docker-compose` runs them all in the same server. This example is intended to show you how you can
split and separate the configuration for each of these pieces.

Because they are deployed in separate containers, you have considerably greater control over what
network traffic gains access to each of these pieces, and they do not all sit under the same Web server. However
because they run in a single Docker-Compose, they must run on different ports, which means you will need further
configuration to expose them in a normal organisation.

image::images/fh_deployment_option_3.svg[Option 2,500]
NOTE: In this `docker-compose` image, there is a database along with an initialization script. If you are wishing
to seriously use this, you will need to run an external database.

=== Option 3 - Scalable Deployment
This option is best if you want to run FeatureHub at scale. Running separate instances of Edge, Cache, NATS and
FeatureHub Server, means you can deploy these components independently for scalability and redundancy.

NOTE: Inorder to scale FeatureHub Server, you need to have first configured a separate database
(see <<Option 2 - Low Volume Deployment>> above).

== Configuration

In the `run-configurations` folder, along with the `docker-compose` configurations you will see that each server has
a set of possible external configurations. If you wish to build and rebundle the images yourself you can easily do this,
the base images, exposed ports and so forth are all configurable as part of the build.

=== Run configuration

By this we mean the properties you can set to control the behaviour of different servers.

==== Management Repository

The following properties can be set:

- `db.url` - the jdbc url of the database server. 
- `db.username` -  the username used to log in.
- `db.password` - the password for the user
- `server.port` - the server port that the server runs on. it always listens to 0.0.0.0 (all network interfaces)
- `nats.urls` - a comma separated list of NATs servers
- `

==== Dacha Config

The following properties can be set (that are meaningful):

- `nats.urls` - a comma separated list of NATs servers

==== SSE-Edge Config



db.url=jdbc:postgresql://db:5432/featurehub
db.username=featurehub
db.password=featurehub
nats.urls=nats://nats:4222

==== Party Server

The party server honours all values set by the Management Repository, Dacha and the the SSE-Edge.

=== Build configurations

Each of the different options, SSE-Edge, Dacha, the Management Repository and the Party Server build docker images
when called from Maven with a cloud image profile.

Make sure the developer build has been completed with:

----
mvn -f pom-first.xml clean install
mvn -T4C clean install
----

If you wish to do individual builds, which we recommend if you are overriding base images and so forth, cd into
those folders. First you will need to make sure the front end builds - it normally builds and installs as part of the
whole build process. Go into the `admin-frontend` folder and type:

----
mvn -Ddocker-cloud-build=true clean install
----

This is a docker build using a Flutter image of the front-end.

Then jump into your chosen folder and your command is:

----
mvn -Ddocker-cloud-build=true -Dapp.baseimage=docker://featurehub/base_mr:1.2 -Dapp.port=8085 -Dbuild.version=0.0.0.1 clean package
----

Where the `app.baseimage`, `app.port` and `build.version` are the versions you specify. The `docker://` prefix just means
it will pull it from Docker. It is using `jib` from Google, so you may wish to further play around with those settings.
