
_Irina to move to Github release notes_

== 1.5.0

This is our first major release in a while and its partly due to feedback we have received and partly our own
requirements moving forward. This releases big announcements are:

- *light-weight edge services* - `edge` splits into *Streaming+REST* and *REST* - so there are now two docker images, the existing one, `edge` which
talks to `dacha` and `edge-rest` which talks directly to the database. This makes `edge-rest` suitable for
deploying into a container runtime platform like KNative, Google Cloud Run or Azure Container Instances.
- *super-light weight bundling* - A new bundled deployment, `party-server-ish` - which contains the admin web app (hosted in nginx), the Admin
App (MR), and edge-rest together as one bundle. It is an ideal deployment for a low-use website and is covered
in our installation docs <insert link Irina>. As it includes `edge-rest` it can't be used for streaming updates,
but if you have a mobile app or web app or you are OK with GET/polling updates, this is a cheap deployment option.
- *enhanced, more performant, rest based cache* - `dacha`, our caching layer moves to being a
REST server from being a NATS server with a monitoring only REST api.
It is intended to be an internal only facing REST service but while it consumes the NATS updates from MR,
it exposes its caching for REST purposes and enhances the data it returns (to include portfolio, application, etc).
If you need to be able to use
this data yourself, its the perfect place to get it from. It will be used in the future for the analytics platform.
This would also let you use a service mesh to tie together edge instances with cache instances.
- *database read replicas* - All systems that talk to databases now support a read replica using the `db-replica.` or `DB-REPLICA_` prefix
for specifying configuration. This means an increased number of database connections, and balancing your read
only queries into the read replicas. This is covered in our installation docs <insert link Irina>
- *open telemetry* - OpenTelemetry support folds into the system, allowing better visibility when you are running it as part of an integrated platform.
- *massive performance increases for GET requests* - Significantly enhanced read operations for GET requests on Edge - we have really focused on performance here
and managed to get a 9x performance improvement for the `dacha` based platform. The `edge-rest` based platform
depends on availability of your database connections so will be a bit slower.
- *reduced data egress costs* - Edge now supports `etag` support and this is now folding into various SDKs. This significantly decreases data
egress costs when features have not changed, and increases the ability to use a CDN in front of Edge if you wish.
- *support for Keycloak* - this adds support for KeyCloak as an identity provider for OAuth2. <insert link Irina>
- *enhanced stats publisher* - Edge can publish stats on how it is being used, this has been enhanced with the
portfolio and application that it is coming from to make it more useful.
