/* 
 * FeatureServiceApi
 *
 * This describes the API clients use for accessing features
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IO.FeatureHub.SSE.Client.OpenAPIDateConverter;

namespace IO.FeatureHub.SSE.Model
{
    /// <summary>
    /// Defines RoleType
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum RoleType
    {
        /// <summary>
        /// Enum READ for value: READ
        /// </summary>
        [EnumMember(Value = "READ")]
        READ = 1,

        /// <summary>
        /// Enum LOCK for value: LOCK
        /// </summary>
        [EnumMember(Value = "LOCK")]
        LOCK = 2,

        /// <summary>
        /// Enum UNLOCK for value: UNLOCK
        /// </summary>
        [EnumMember(Value = "UNLOCK")]
        UNLOCK = 3,

        /// <summary>
        /// Enum CHANGEVALUE for value: CHANGE_VALUE
        /// </summary>
        [EnumMember(Value = "CHANGE_VALUE")]
        CHANGEVALUE = 4

    }

}
