/* 
 * FeatureServiceApi
 *
 * This describes the API clients use for accessing features
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = IO.FeatureHub.SSE.Client.OpenAPIDateConverter;

namespace IO.FeatureHub.SSE.Model
{
    /// <summary>
    /// Defines RolloutStrategyFieldType
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum RolloutStrategyFieldType
    {
        /// <summary>
        /// Enum STRING for value: STRING
        /// </summary>
        [EnumMember(Value = "STRING")]
        STRING = 1,

        /// <summary>
        /// Enum SEMANTICVERSION for value: SEMANTIC_VERSION
        /// </summary>
        [EnumMember(Value = "SEMANTIC_VERSION")]
        SEMANTICVERSION = 2,

        /// <summary>
        /// Enum NUMBER for value: NUMBER
        /// </summary>
        [EnumMember(Value = "NUMBER")]
        NUMBER = 3,

        /// <summary>
        /// Enum DATE for value: DATE
        /// </summary>
        [EnumMember(Value = "DATE")]
        DATE = 4,

        /// <summary>
        /// Enum DATETIME for value: DATETIME
        /// </summary>
        [EnumMember(Value = "DATETIME")]
        DATETIME = 5,

        /// <summary>
        /// Enum BOOLEAN for value: BOOLEAN
        /// </summary>
        [EnumMember(Value = "BOOLEAN")]
        BOOLEAN = 6,

        /// <summary>
        /// Enum IPADDRESS for value: IP_ADDRESS
        /// </summary>
        [EnumMember(Value = "IP_ADDRESS")]
        IPADDRESS = 7

    }

}
