/* 
 * FeatureServiceApi
 *
 * This describes the API clients use for accessing features
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = IO.FeatureHub.SSE.Client.OpenAPIDateConverter;

namespace IO.FeatureHub.SSE.Model
{
    /// <summary>
    /// Defines StrategyAttributeWellKnownNames
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum StrategyAttributeWellKnownNames
    {
        /// <summary>
        /// Enum Device for value: device
        /// </summary>
        [EnumMember(Value = "device")]
        Device = 1,

        /// <summary>
        /// Enum Country for value: country
        /// </summary>
        [EnumMember(Value = "country")]
        Country = 2,

        /// <summary>
        /// Enum Platform for value: platform
        /// </summary>
        [EnumMember(Value = "platform")]
        Platform = 3,

        /// <summary>
        /// Enum Userkey for value: userkey
        /// </summary>
        [EnumMember(Value = "userkey")]
        Userkey = 4,

        /// <summary>
        /// Enum Session for value: session
        /// </summary>
        [EnumMember(Value = "session")]
        Session = 5,

        /// <summary>
        /// Enum Version for value: version
        /// </summary>
        [EnumMember(Value = "version")]
        Version = 6

    }

}
