/* 
 * FeatureServiceApi
 *
 * This describes the API clients use for accessing features
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = IO.FeatureHub.SSE.Client.OpenAPIDateConverter;

namespace IO.FeatureHub.SSE.Model
{
    /// <summary>
    /// Defines StrategyAttributePlatformName
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum StrategyAttributePlatformName
    {
        /// <summary>
        /// Enum Linux for value: linux
        /// </summary>
        [EnumMember(Value = "linux")]
        Linux = 1,

        /// <summary>
        /// Enum Windows for value: windows
        /// </summary>
        [EnumMember(Value = "windows")]
        Windows = 2,

        /// <summary>
        /// Enum Macos for value: macos
        /// </summary>
        [EnumMember(Value = "macos")]
        Macos = 3,

        /// <summary>
        /// Enum Android for value: android
        /// </summary>
        [EnumMember(Value = "android")]
        Android = 4,

        /// <summary>
        /// Enum Ios for value: ios
        /// </summary>
        [EnumMember(Value = "ios")]
        Ios = 5

    }

}
