/* 
 * FeatureServiceApi
 *
 * This describes the API clients use for accessing features
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = IO.FeatureHub.SSE.Client.OpenAPIDateConverter;

namespace IO.FeatureHub.SSE.Model
{
    /// <summary>
    /// https://www.britannica.com/topic/list-of-countries-1993160 - we put these in API so everyone can have the same list
    /// </summary>
    /// <value>https://www.britannica.com/topic/list-of-countries-1993160 - we put these in API so everyone can have the same list</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum StrategyAttributeCountryName
    {
        /// <summary>
        /// Enum Afghanistan for value: afghanistan
        /// </summary>
        [EnumMember(Value = "afghanistan")]
        Afghanistan = 1,

        /// <summary>
        /// Enum Albania for value: albania
        /// </summary>
        [EnumMember(Value = "albania")]
        Albania = 2,

        /// <summary>
        /// Enum Algeria for value: algeria
        /// </summary>
        [EnumMember(Value = "algeria")]
        Algeria = 3,

        /// <summary>
        /// Enum Andorra for value: andorra
        /// </summary>
        [EnumMember(Value = "andorra")]
        Andorra = 4,

        /// <summary>
        /// Enum Angola for value: angola
        /// </summary>
        [EnumMember(Value = "angola")]
        Angola = 5,

        /// <summary>
        /// Enum Antiguaandbarbuda for value: antigua_and_barbuda
        /// </summary>
        [EnumMember(Value = "antigua_and_barbuda")]
        Antiguaandbarbuda = 6,

        /// <summary>
        /// Enum Argentina for value: argentina
        /// </summary>
        [EnumMember(Value = "argentina")]
        Argentina = 7,

        /// <summary>
        /// Enum Armenia for value: armenia
        /// </summary>
        [EnumMember(Value = "armenia")]
        Armenia = 8,

        /// <summary>
        /// Enum Australia for value: australia
        /// </summary>
        [EnumMember(Value = "australia")]
        Australia = 9,

        /// <summary>
        /// Enum Austria for value: austria
        /// </summary>
        [EnumMember(Value = "austria")]
        Austria = 10,

        /// <summary>
        /// Enum Azerbaijan for value: azerbaijan
        /// </summary>
        [EnumMember(Value = "azerbaijan")]
        Azerbaijan = 11,

        /// <summary>
        /// Enum Thebahamas for value: the_bahamas
        /// </summary>
        [EnumMember(Value = "the_bahamas")]
        Thebahamas = 12,

        /// <summary>
        /// Enum Bahrain for value: bahrain
        /// </summary>
        [EnumMember(Value = "bahrain")]
        Bahrain = 13,

        /// <summary>
        /// Enum Bangladesh for value: bangladesh
        /// </summary>
        [EnumMember(Value = "bangladesh")]
        Bangladesh = 14,

        /// <summary>
        /// Enum Barbados for value: barbados
        /// </summary>
        [EnumMember(Value = "barbados")]
        Barbados = 15,

        /// <summary>
        /// Enum Belarus for value: belarus
        /// </summary>
        [EnumMember(Value = "belarus")]
        Belarus = 16,

        /// <summary>
        /// Enum Belgium for value: belgium
        /// </summary>
        [EnumMember(Value = "belgium")]
        Belgium = 17,

        /// <summary>
        /// Enum Belize for value: belize
        /// </summary>
        [EnumMember(Value = "belize")]
        Belize = 18,

        /// <summary>
        /// Enum Benin for value: benin
        /// </summary>
        [EnumMember(Value = "benin")]
        Benin = 19,

        /// <summary>
        /// Enum Bhutan for value: bhutan
        /// </summary>
        [EnumMember(Value = "bhutan")]
        Bhutan = 20,

        /// <summary>
        /// Enum Bolivia for value: bolivia
        /// </summary>
        [EnumMember(Value = "bolivia")]
        Bolivia = 21,

        /// <summary>
        /// Enum Bosniaandherzegovina for value: bosnia_and_herzegovina
        /// </summary>
        [EnumMember(Value = "bosnia_and_herzegovina")]
        Bosniaandherzegovina = 22,

        /// <summary>
        /// Enum Botswana for value: botswana
        /// </summary>
        [EnumMember(Value = "botswana")]
        Botswana = 23,

        /// <summary>
        /// Enum Brazil for value: brazil
        /// </summary>
        [EnumMember(Value = "brazil")]
        Brazil = 24,

        /// <summary>
        /// Enum Brunei for value: brunei
        /// </summary>
        [EnumMember(Value = "brunei")]
        Brunei = 25,

        /// <summary>
        /// Enum Bulgaria for value: bulgaria
        /// </summary>
        [EnumMember(Value = "bulgaria")]
        Bulgaria = 26,

        /// <summary>
        /// Enum Burkinafaso for value: burkina_faso
        /// </summary>
        [EnumMember(Value = "burkina_faso")]
        Burkinafaso = 27,

        /// <summary>
        /// Enum Burundi for value: burundi
        /// </summary>
        [EnumMember(Value = "burundi")]
        Burundi = 28,

        /// <summary>
        /// Enum Caboverde for value: cabo_verde
        /// </summary>
        [EnumMember(Value = "cabo_verde")]
        Caboverde = 29,

        /// <summary>
        /// Enum Cambodia for value: cambodia
        /// </summary>
        [EnumMember(Value = "cambodia")]
        Cambodia = 30,

        /// <summary>
        /// Enum Cameroon for value: cameroon
        /// </summary>
        [EnumMember(Value = "cameroon")]
        Cameroon = 31,

        /// <summary>
        /// Enum Canada for value: canada
        /// </summary>
        [EnumMember(Value = "canada")]
        Canada = 32,

        /// <summary>
        /// Enum Centralafricanrepublic for value: central_african_republic
        /// </summary>
        [EnumMember(Value = "central_african_republic")]
        Centralafricanrepublic = 33,

        /// <summary>
        /// Enum Chad for value: chad
        /// </summary>
        [EnumMember(Value = "chad")]
        Chad = 34,

        /// <summary>
        /// Enum Chile for value: chile
        /// </summary>
        [EnumMember(Value = "chile")]
        Chile = 35,

        /// <summary>
        /// Enum China for value: china
        /// </summary>
        [EnumMember(Value = "china")]
        China = 36,

        /// <summary>
        /// Enum Colombia for value: colombia
        /// </summary>
        [EnumMember(Value = "colombia")]
        Colombia = 37,

        /// <summary>
        /// Enum Comoros for value: comoros
        /// </summary>
        [EnumMember(Value = "comoros")]
        Comoros = 38,

        /// <summary>
        /// Enum Congodemocraticrepublicofthe for value: congo_democratic_republic_of_the
        /// </summary>
        [EnumMember(Value = "congo_democratic_republic_of_the")]
        Congodemocraticrepublicofthe = 39,

        /// <summary>
        /// Enum Congorepublicofthe for value: congo_republic_of_the
        /// </summary>
        [EnumMember(Value = "congo_republic_of_the")]
        Congorepublicofthe = 40,

        /// <summary>
        /// Enum Costarica for value: costa_rica
        /// </summary>
        [EnumMember(Value = "costa_rica")]
        Costarica = 41,

        /// <summary>
        /// Enum Cotedivoire for value: cote_divoire
        /// </summary>
        [EnumMember(Value = "cote_divoire")]
        Cotedivoire = 42,

        /// <summary>
        /// Enum Croatia for value: croatia
        /// </summary>
        [EnumMember(Value = "croatia")]
        Croatia = 43,

        /// <summary>
        /// Enum Cuba for value: cuba
        /// </summary>
        [EnumMember(Value = "cuba")]
        Cuba = 44,

        /// <summary>
        /// Enum Cyprus for value: cyprus
        /// </summary>
        [EnumMember(Value = "cyprus")]
        Cyprus = 45,

        /// <summary>
        /// Enum Czechrepublic for value: czech_republic
        /// </summary>
        [EnumMember(Value = "czech_republic")]
        Czechrepublic = 46,

        /// <summary>
        /// Enum Denmark for value: denmark
        /// </summary>
        [EnumMember(Value = "denmark")]
        Denmark = 47,

        /// <summary>
        /// Enum Djibouti for value: djibouti
        /// </summary>
        [EnumMember(Value = "djibouti")]
        Djibouti = 48,

        /// <summary>
        /// Enum Dominica for value: dominica
        /// </summary>
        [EnumMember(Value = "dominica")]
        Dominica = 49,

        /// <summary>
        /// Enum Dominicanrepublic for value: dominican_republic
        /// </summary>
        [EnumMember(Value = "dominican_republic")]
        Dominicanrepublic = 50,

        /// <summary>
        /// Enum Easttimor for value: east_timor
        /// </summary>
        [EnumMember(Value = "east_timor")]
        Easttimor = 51,

        /// <summary>
        /// Enum Ecuador for value: ecuador
        /// </summary>
        [EnumMember(Value = "ecuador")]
        Ecuador = 52,

        /// <summary>
        /// Enum Egypt for value: egypt
        /// </summary>
        [EnumMember(Value = "egypt")]
        Egypt = 53,

        /// <summary>
        /// Enum Elsalvador for value: el_salvador
        /// </summary>
        [EnumMember(Value = "el_salvador")]
        Elsalvador = 54,

        /// <summary>
        /// Enum Equatorialguinea for value: equatorial_guinea
        /// </summary>
        [EnumMember(Value = "equatorial_guinea")]
        Equatorialguinea = 55,

        /// <summary>
        /// Enum Eritrea for value: eritrea
        /// </summary>
        [EnumMember(Value = "eritrea")]
        Eritrea = 56,

        /// <summary>
        /// Enum Estonia for value: estonia
        /// </summary>
        [EnumMember(Value = "estonia")]
        Estonia = 57,

        /// <summary>
        /// Enum Eswatini for value: eswatini
        /// </summary>
        [EnumMember(Value = "eswatini")]
        Eswatini = 58,

        /// <summary>
        /// Enum Ethiopia for value: ethiopia
        /// </summary>
        [EnumMember(Value = "ethiopia")]
        Ethiopia = 59,

        /// <summary>
        /// Enum Fiji for value: fiji
        /// </summary>
        [EnumMember(Value = "fiji")]
        Fiji = 60,

        /// <summary>
        /// Enum Finland for value: finland
        /// </summary>
        [EnumMember(Value = "finland")]
        Finland = 61,

        /// <summary>
        /// Enum France for value: france
        /// </summary>
        [EnumMember(Value = "france")]
        France = 62,

        /// <summary>
        /// Enum Gabon for value: gabon
        /// </summary>
        [EnumMember(Value = "gabon")]
        Gabon = 63,

        /// <summary>
        /// Enum Thegambia for value: the_gambia
        /// </summary>
        [EnumMember(Value = "the_gambia")]
        Thegambia = 64,

        /// <summary>
        /// Enum Georgia for value: georgia
        /// </summary>
        [EnumMember(Value = "georgia")]
        Georgia = 65,

        /// <summary>
        /// Enum Germany for value: germany
        /// </summary>
        [EnumMember(Value = "germany")]
        Germany = 66,

        /// <summary>
        /// Enum Ghana for value: ghana
        /// </summary>
        [EnumMember(Value = "ghana")]
        Ghana = 67,

        /// <summary>
        /// Enum Greece for value: greece
        /// </summary>
        [EnumMember(Value = "greece")]
        Greece = 68,

        /// <summary>
        /// Enum Grenada for value: grenada
        /// </summary>
        [EnumMember(Value = "grenada")]
        Grenada = 69,

        /// <summary>
        /// Enum Guatemala for value: guatemala
        /// </summary>
        [EnumMember(Value = "guatemala")]
        Guatemala = 70,

        /// <summary>
        /// Enum Guinea for value: guinea
        /// </summary>
        [EnumMember(Value = "guinea")]
        Guinea = 71,

        /// <summary>
        /// Enum Guineabissau for value: guinea_bissau
        /// </summary>
        [EnumMember(Value = "guinea_bissau")]
        Guineabissau = 72,

        /// <summary>
        /// Enum Guyana for value: guyana
        /// </summary>
        [EnumMember(Value = "guyana")]
        Guyana = 73,

        /// <summary>
        /// Enum Haiti for value: haiti
        /// </summary>
        [EnumMember(Value = "haiti")]
        Haiti = 74,

        /// <summary>
        /// Enum Honduras for value: honduras
        /// </summary>
        [EnumMember(Value = "honduras")]
        Honduras = 75,

        /// <summary>
        /// Enum Hungary for value: hungary
        /// </summary>
        [EnumMember(Value = "hungary")]
        Hungary = 76,

        /// <summary>
        /// Enum Iceland for value: iceland
        /// </summary>
        [EnumMember(Value = "iceland")]
        Iceland = 77,

        /// <summary>
        /// Enum India for value: india
        /// </summary>
        [EnumMember(Value = "india")]
        India = 78,

        /// <summary>
        /// Enum Indonesia for value: indonesia
        /// </summary>
        [EnumMember(Value = "indonesia")]
        Indonesia = 79,

        /// <summary>
        /// Enum Iran for value: iran
        /// </summary>
        [EnumMember(Value = "iran")]
        Iran = 80,

        /// <summary>
        /// Enum Iraq for value: iraq
        /// </summary>
        [EnumMember(Value = "iraq")]
        Iraq = 81,

        /// <summary>
        /// Enum Ireland for value: ireland
        /// </summary>
        [EnumMember(Value = "ireland")]
        Ireland = 82,

        /// <summary>
        /// Enum Israel for value: israel
        /// </summary>
        [EnumMember(Value = "israel")]
        Israel = 83,

        /// <summary>
        /// Enum Italy for value: italy
        /// </summary>
        [EnumMember(Value = "italy")]
        Italy = 84,

        /// <summary>
        /// Enum Jamaica for value: jamaica
        /// </summary>
        [EnumMember(Value = "jamaica")]
        Jamaica = 85,

        /// <summary>
        /// Enum Japan for value: japan
        /// </summary>
        [EnumMember(Value = "japan")]
        Japan = 86,

        /// <summary>
        /// Enum Jordan for value: jordan
        /// </summary>
        [EnumMember(Value = "jordan")]
        Jordan = 87,

        /// <summary>
        /// Enum Kazakhstan for value: kazakhstan
        /// </summary>
        [EnumMember(Value = "kazakhstan")]
        Kazakhstan = 88,

        /// <summary>
        /// Enum Kenya for value: kenya
        /// </summary>
        [EnumMember(Value = "kenya")]
        Kenya = 89,

        /// <summary>
        /// Enum Kiribati for value: kiribati
        /// </summary>
        [EnumMember(Value = "kiribati")]
        Kiribati = 90,

        /// <summary>
        /// Enum Koreanorth for value: korea_north
        /// </summary>
        [EnumMember(Value = "korea_north")]
        Koreanorth = 91,

        /// <summary>
        /// Enum Koreasouth for value: korea_south
        /// </summary>
        [EnumMember(Value = "korea_south")]
        Koreasouth = 92,

        /// <summary>
        /// Enum Kosovo for value: kosovo
        /// </summary>
        [EnumMember(Value = "kosovo")]
        Kosovo = 93,

        /// <summary>
        /// Enum Kuwait for value: kuwait
        /// </summary>
        [EnumMember(Value = "kuwait")]
        Kuwait = 94,

        /// <summary>
        /// Enum Kyrgyzstan for value: kyrgyzstan
        /// </summary>
        [EnumMember(Value = "kyrgyzstan")]
        Kyrgyzstan = 95,

        /// <summary>
        /// Enum Laos for value: laos
        /// </summary>
        [EnumMember(Value = "laos")]
        Laos = 96,

        /// <summary>
        /// Enum Latvia for value: latvia
        /// </summary>
        [EnumMember(Value = "latvia")]
        Latvia = 97,

        /// <summary>
        /// Enum Lebanon for value: lebanon
        /// </summary>
        [EnumMember(Value = "lebanon")]
        Lebanon = 98,

        /// <summary>
        /// Enum Lesotho for value: lesotho
        /// </summary>
        [EnumMember(Value = "lesotho")]
        Lesotho = 99,

        /// <summary>
        /// Enum Liberia for value: liberia
        /// </summary>
        [EnumMember(Value = "liberia")]
        Liberia = 100,

        /// <summary>
        /// Enum Libya for value: libya
        /// </summary>
        [EnumMember(Value = "libya")]
        Libya = 101,

        /// <summary>
        /// Enum Liechtenstein for value: liechtenstein
        /// </summary>
        [EnumMember(Value = "liechtenstein")]
        Liechtenstein = 102,

        /// <summary>
        /// Enum Lithuania for value: lithuania
        /// </summary>
        [EnumMember(Value = "lithuania")]
        Lithuania = 103,

        /// <summary>
        /// Enum Luxembourg for value: luxembourg
        /// </summary>
        [EnumMember(Value = "luxembourg")]
        Luxembourg = 104,

        /// <summary>
        /// Enum Madagascar for value: madagascar
        /// </summary>
        [EnumMember(Value = "madagascar")]
        Madagascar = 105,

        /// <summary>
        /// Enum Malawi for value: malawi
        /// </summary>
        [EnumMember(Value = "malawi")]
        Malawi = 106,

        /// <summary>
        /// Enum Malaysia for value: malaysia
        /// </summary>
        [EnumMember(Value = "malaysia")]
        Malaysia = 107,

        /// <summary>
        /// Enum Maldives for value: maldives
        /// </summary>
        [EnumMember(Value = "maldives")]
        Maldives = 108,

        /// <summary>
        /// Enum Mali for value: mali
        /// </summary>
        [EnumMember(Value = "mali")]
        Mali = 109,

        /// <summary>
        /// Enum Malta for value: malta
        /// </summary>
        [EnumMember(Value = "malta")]
        Malta = 110,

        /// <summary>
        /// Enum Marshallislands for value: marshall_islands
        /// </summary>
        [EnumMember(Value = "marshall_islands")]
        Marshallislands = 111,

        /// <summary>
        /// Enum Mauritania for value: mauritania
        /// </summary>
        [EnumMember(Value = "mauritania")]
        Mauritania = 112,

        /// <summary>
        /// Enum Mauritius for value: mauritius
        /// </summary>
        [EnumMember(Value = "mauritius")]
        Mauritius = 113,

        /// <summary>
        /// Enum Mexico for value: mexico
        /// </summary>
        [EnumMember(Value = "mexico")]
        Mexico = 114,

        /// <summary>
        /// Enum Micronesiafederatedstatesof for value: micronesia_federated_states_of
        /// </summary>
        [EnumMember(Value = "micronesia_federated_states_of")]
        Micronesiafederatedstatesof = 115,

        /// <summary>
        /// Enum Moldova for value: moldova
        /// </summary>
        [EnumMember(Value = "moldova")]
        Moldova = 116,

        /// <summary>
        /// Enum Monaco for value: monaco
        /// </summary>
        [EnumMember(Value = "monaco")]
        Monaco = 117,

        /// <summary>
        /// Enum Mongolia for value: mongolia
        /// </summary>
        [EnumMember(Value = "mongolia")]
        Mongolia = 118,

        /// <summary>
        /// Enum Montenegro for value: montenegro
        /// </summary>
        [EnumMember(Value = "montenegro")]
        Montenegro = 119,

        /// <summary>
        /// Enum Morocco for value: morocco
        /// </summary>
        [EnumMember(Value = "morocco")]
        Morocco = 120,

        /// <summary>
        /// Enum Mozambique for value: mozambique
        /// </summary>
        [EnumMember(Value = "mozambique")]
        Mozambique = 121,

        /// <summary>
        /// Enum Myanmar for value: myanmar
        /// </summary>
        [EnumMember(Value = "myanmar")]
        Myanmar = 122,

        /// <summary>
        /// Enum Namibia for value: namibia
        /// </summary>
        [EnumMember(Value = "namibia")]
        Namibia = 123,

        /// <summary>
        /// Enum Nauru for value: nauru
        /// </summary>
        [EnumMember(Value = "nauru")]
        Nauru = 124,

        /// <summary>
        /// Enum Nepal for value: nepal
        /// </summary>
        [EnumMember(Value = "nepal")]
        Nepal = 125,

        /// <summary>
        /// Enum Netherlands for value: netherlands
        /// </summary>
        [EnumMember(Value = "netherlands")]
        Netherlands = 126,

        /// <summary>
        /// Enum Newzealand for value: new_zealand
        /// </summary>
        [EnumMember(Value = "new_zealand")]
        Newzealand = 127,

        /// <summary>
        /// Enum Nicaragua for value: nicaragua
        /// </summary>
        [EnumMember(Value = "nicaragua")]
        Nicaragua = 128,

        /// <summary>
        /// Enum Niger for value: niger
        /// </summary>
        [EnumMember(Value = "niger")]
        Niger = 129,

        /// <summary>
        /// Enum Nigeria for value: nigeria
        /// </summary>
        [EnumMember(Value = "nigeria")]
        Nigeria = 130,

        /// <summary>
        /// Enum Northmacedonia for value: north_macedonia
        /// </summary>
        [EnumMember(Value = "north_macedonia")]
        Northmacedonia = 131,

        /// <summary>
        /// Enum Norway for value: norway
        /// </summary>
        [EnumMember(Value = "norway")]
        Norway = 132,

        /// <summary>
        /// Enum Oman for value: oman
        /// </summary>
        [EnumMember(Value = "oman")]
        Oman = 133,

        /// <summary>
        /// Enum Pakistan for value: pakistan
        /// </summary>
        [EnumMember(Value = "pakistan")]
        Pakistan = 134,

        /// <summary>
        /// Enum Palau for value: palau
        /// </summary>
        [EnumMember(Value = "palau")]
        Palau = 135,

        /// <summary>
        /// Enum Panama for value: panama
        /// </summary>
        [EnumMember(Value = "panama")]
        Panama = 136,

        /// <summary>
        /// Enum Papuanewguinea for value: papua_new_guinea
        /// </summary>
        [EnumMember(Value = "papua_new_guinea")]
        Papuanewguinea = 137,

        /// <summary>
        /// Enum Paraguay for value: paraguay
        /// </summary>
        [EnumMember(Value = "paraguay")]
        Paraguay = 138,

        /// <summary>
        /// Enum Peru for value: peru
        /// </summary>
        [EnumMember(Value = "peru")]
        Peru = 139,

        /// <summary>
        /// Enum Philippines for value: philippines
        /// </summary>
        [EnumMember(Value = "philippines")]
        Philippines = 140,

        /// <summary>
        /// Enum Poland for value: poland
        /// </summary>
        [EnumMember(Value = "poland")]
        Poland = 141,

        /// <summary>
        /// Enum Portugal for value: portugal
        /// </summary>
        [EnumMember(Value = "portugal")]
        Portugal = 142,

        /// <summary>
        /// Enum Qatar for value: qatar
        /// </summary>
        [EnumMember(Value = "qatar")]
        Qatar = 143,

        /// <summary>
        /// Enum Romania for value: romania
        /// </summary>
        [EnumMember(Value = "romania")]
        Romania = 144,

        /// <summary>
        /// Enum Russia for value: russia
        /// </summary>
        [EnumMember(Value = "russia")]
        Russia = 145,

        /// <summary>
        /// Enum Rwanda for value: rwanda
        /// </summary>
        [EnumMember(Value = "rwanda")]
        Rwanda = 146,

        /// <summary>
        /// Enum Saintkittsandnevis for value: saint_kitts_and_nevis
        /// </summary>
        [EnumMember(Value = "saint_kitts_and_nevis")]
        Saintkittsandnevis = 147,

        /// <summary>
        /// Enum Saintlucia for value: saint_lucia
        /// </summary>
        [EnumMember(Value = "saint_lucia")]
        Saintlucia = 148,

        /// <summary>
        /// Enum Saintvincentandthegrenadines for value: saint_vincent_and_the_grenadines
        /// </summary>
        [EnumMember(Value = "saint_vincent_and_the_grenadines")]
        Saintvincentandthegrenadines = 149,

        /// <summary>
        /// Enum Samoa for value: samoa
        /// </summary>
        [EnumMember(Value = "samoa")]
        Samoa = 150,

        /// <summary>
        /// Enum Sanmarino for value: san_marino
        /// </summary>
        [EnumMember(Value = "san_marino")]
        Sanmarino = 151,

        /// <summary>
        /// Enum Saotomeandprincipe for value: sao_tome_and_principe
        /// </summary>
        [EnumMember(Value = "sao_tome_and_principe")]
        Saotomeandprincipe = 152,

        /// <summary>
        /// Enum Saudiarabia for value: saudi_arabia
        /// </summary>
        [EnumMember(Value = "saudi_arabia")]
        Saudiarabia = 153,

        /// <summary>
        /// Enum Senegal for value: senegal
        /// </summary>
        [EnumMember(Value = "senegal")]
        Senegal = 154,

        /// <summary>
        /// Enum Serbia for value: serbia
        /// </summary>
        [EnumMember(Value = "serbia")]
        Serbia = 155,

        /// <summary>
        /// Enum Seychelles for value: seychelles
        /// </summary>
        [EnumMember(Value = "seychelles")]
        Seychelles = 156,

        /// <summary>
        /// Enum Sierraleone for value: sierra_leone
        /// </summary>
        [EnumMember(Value = "sierra_leone")]
        Sierraleone = 157,

        /// <summary>
        /// Enum Singapore for value: singapore
        /// </summary>
        [EnumMember(Value = "singapore")]
        Singapore = 158,

        /// <summary>
        /// Enum Slovakia for value: slovakia
        /// </summary>
        [EnumMember(Value = "slovakia")]
        Slovakia = 159,

        /// <summary>
        /// Enum Slovenia for value: slovenia
        /// </summary>
        [EnumMember(Value = "slovenia")]
        Slovenia = 160,

        /// <summary>
        /// Enum Solomonislands for value: solomon_islands
        /// </summary>
        [EnumMember(Value = "solomon_islands")]
        Solomonislands = 161,

        /// <summary>
        /// Enum Somalia for value: somalia
        /// </summary>
        [EnumMember(Value = "somalia")]
        Somalia = 162,

        /// <summary>
        /// Enum Southafrica for value: south_africa
        /// </summary>
        [EnumMember(Value = "south_africa")]
        Southafrica = 163,

        /// <summary>
        /// Enum Spain for value: spain
        /// </summary>
        [EnumMember(Value = "spain")]
        Spain = 164,

        /// <summary>
        /// Enum Srilanka for value: sri_lanka
        /// </summary>
        [EnumMember(Value = "sri_lanka")]
        Srilanka = 165,

        /// <summary>
        /// Enum Sudan for value: sudan
        /// </summary>
        [EnumMember(Value = "sudan")]
        Sudan = 166,

        /// <summary>
        /// Enum Sudansouth for value: sudan_south
        /// </summary>
        [EnumMember(Value = "sudan_south")]
        Sudansouth = 167,

        /// <summary>
        /// Enum Suriname for value: suriname
        /// </summary>
        [EnumMember(Value = "suriname")]
        Suriname = 168,

        /// <summary>
        /// Enum Sweden for value: sweden
        /// </summary>
        [EnumMember(Value = "sweden")]
        Sweden = 169,

        /// <summary>
        /// Enum Switzerland for value: switzerland
        /// </summary>
        [EnumMember(Value = "switzerland")]
        Switzerland = 170,

        /// <summary>
        /// Enum Syria for value: syria
        /// </summary>
        [EnumMember(Value = "syria")]
        Syria = 171,

        /// <summary>
        /// Enum Taiwan for value: taiwan
        /// </summary>
        [EnumMember(Value = "taiwan")]
        Taiwan = 172,

        /// <summary>
        /// Enum Tajikistan for value: tajikistan
        /// </summary>
        [EnumMember(Value = "tajikistan")]
        Tajikistan = 173,

        /// <summary>
        /// Enum Tanzania for value: tanzania
        /// </summary>
        [EnumMember(Value = "tanzania")]
        Tanzania = 174,

        /// <summary>
        /// Enum Thailand for value: thailand
        /// </summary>
        [EnumMember(Value = "thailand")]
        Thailand = 175,

        /// <summary>
        /// Enum Togo for value: togo
        /// </summary>
        [EnumMember(Value = "togo")]
        Togo = 176,

        /// <summary>
        /// Enum Tonga for value: tonga
        /// </summary>
        [EnumMember(Value = "tonga")]
        Tonga = 177,

        /// <summary>
        /// Enum Trinidadandtobago for value: trinidad_and_tobago
        /// </summary>
        [EnumMember(Value = "trinidad_and_tobago")]
        Trinidadandtobago = 178,

        /// <summary>
        /// Enum Tunisia for value: tunisia
        /// </summary>
        [EnumMember(Value = "tunisia")]
        Tunisia = 179,

        /// <summary>
        /// Enum Turkey for value: turkey
        /// </summary>
        [EnumMember(Value = "turkey")]
        Turkey = 180,

        /// <summary>
        /// Enum Turkmenistan for value: turkmenistan
        /// </summary>
        [EnumMember(Value = "turkmenistan")]
        Turkmenistan = 181,

        /// <summary>
        /// Enum Tuvalu for value: tuvalu
        /// </summary>
        [EnumMember(Value = "tuvalu")]
        Tuvalu = 182,

        /// <summary>
        /// Enum Uganda for value: uganda
        /// </summary>
        [EnumMember(Value = "uganda")]
        Uganda = 183,

        /// <summary>
        /// Enum Ukraine for value: ukraine
        /// </summary>
        [EnumMember(Value = "ukraine")]
        Ukraine = 184,

        /// <summary>
        /// Enum Unitedarabemirates for value: united_arab_emirates
        /// </summary>
        [EnumMember(Value = "united_arab_emirates")]
        Unitedarabemirates = 185,

        /// <summary>
        /// Enum Unitedkingdom for value: united_kingdom
        /// </summary>
        [EnumMember(Value = "united_kingdom")]
        Unitedkingdom = 186,

        /// <summary>
        /// Enum Unitedstates for value: united_states
        /// </summary>
        [EnumMember(Value = "united_states")]
        Unitedstates = 187,

        /// <summary>
        /// Enum Uruguay for value: uruguay
        /// </summary>
        [EnumMember(Value = "uruguay")]
        Uruguay = 188,

        /// <summary>
        /// Enum Uzbekistan for value: uzbekistan
        /// </summary>
        [EnumMember(Value = "uzbekistan")]
        Uzbekistan = 189,

        /// <summary>
        /// Enum Vanuatu for value: vanuatu
        /// </summary>
        [EnumMember(Value = "vanuatu")]
        Vanuatu = 190,

        /// <summary>
        /// Enum Vaticancity for value: vatican_city
        /// </summary>
        [EnumMember(Value = "vatican_city")]
        Vaticancity = 191,

        /// <summary>
        /// Enum Venezuela for value: venezuela
        /// </summary>
        [EnumMember(Value = "venezuela")]
        Venezuela = 192,

        /// <summary>
        /// Enum Vietnam for value: vietnam
        /// </summary>
        [EnumMember(Value = "vietnam")]
        Vietnam = 193,

        /// <summary>
        /// Enum Yemen for value: yemen
        /// </summary>
        [EnumMember(Value = "yemen")]
        Yemen = 194,

        /// <summary>
        /// Enum Zambia for value: zambia
        /// </summary>
        [EnumMember(Value = "zambia")]
        Zambia = 195,

        /// <summary>
        /// Enum Zimbabwe for value: zimbabwe
        /// </summary>
        [EnumMember(Value = "zimbabwe")]
        Zimbabwe = 196

    }

}
