/* tslint:disable */
/* eslint-disable */
/**
 * FeatureServiceApi
 * This describes the API clients use for accessing features
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { FeatureValueType } from './feature-value-type';
  import { RolloutStrategy } from './rollout-strategy';

  /**
* 
* @export
* @class FeatureState
*/
export class FeatureState {
  /**
  * 
  * @type {string}
  * @memberof FeatureState
  */
  public id?: string;
  /**
  * 
  * @type {string}
  * @memberof FeatureState
  */
  public key?: string;
  /**
  * Is this feature locked. Usually this doesn\'t matter because the value is the value, but for FeatureInterceptors it can matter.
  * @type {boolean}
  * @memberof FeatureState
  */
  public l?: boolean;
  /**
  * The version of the feature, this allows features to change values and it means we don\'t trigger events
  * @type {number}
  * @memberof FeatureState
  */
  public version?: number;
  /**
  * 
  * @type {FeatureValueType}
  * @memberof FeatureState
  */
  public type?: FeatureValueType;
  /**
  * the current value
  * @type {any}
  * @memberof FeatureState
  */
  public value?: any | null;
  /**
  * This field is filled in from the client side in the GET api as the GET api is able to request multiple environments. It is never passed from the server, as an array of feature states is wrapped in an environment.
  * @type {string}
  * @memberof FeatureState
  */
  public environmentId?: string;
  /**
  * 
  * @type {Array<RolloutStrategy>}
  * @memberof FeatureState
  */
  public strategies?: Array<RolloutStrategy>;

  constructor(init?: Partial<FeatureState>) {
    Object.assign(this, init);
  }
}


