openapi: 3.0.1
info:
  title: FeatureServiceApi
  description: This describes the API clients use for accessing features
  version: "1.1.2"
paths:
  /features/:
    get:
      tags:
        - FeatureService
      parameters:
        - name: sdkUrl
          in: query
          description: "The SDK urls"
          required: true
          schema:
            type: array
            items:
              type: string
      description: Requests all features for this sdkurl and disconnects
      operationId: getFeatureStates
      responses:
        "200":
          description: feature request successful, all environments you have permission to or that were found are returned
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Environment"
        "400":
          description: you didn't ask for any environments
          content:
            application/json:
              schema:
                {}
  /features/{sdkUrl}/{featureKey}:
    put:
      tags:
        - FeatureService
      parameters:
        - name: sdkUrl
          in: path
          description: "The SDK key for the environment and service account"
          required: true
          schema:
            type: string
        - name: featureKey
          in: path
          description: "The key you wish to update/action"
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FeatureStateUpdate"
      description: "Updates the feature state if allowed."
      operationId: setFeatureState
      responses:
        "200":
          description: update was accepted but not actioned because feature is already in that state
          content:
            application/json:
              schema:
                {}
        "201":
          description: update was accepted and actioned
          content:
            application/json:
              schema:
                {}
        "202":
          description: Neither lock or value was changing
          content:
            application/json:
              schema:
                {}
        "400":
          description: you have made a request that doesn't make sense. e.g. it has no data
          content:
            application/json:
              schema:
                {}
        "403":
          description: update was not accepted, attempted change is outside the permissions of this user
          content:
            application/json:
              schema:
                {}
        "404":
          description: something about the presented data isn't right and we couldn't find it, could be the service key, the environment or the feature
          content:
            application/json:
              schema:
                {}
        "412":
          description: you have made a request that isn't possible. e.g. changing a value without unlocking it.
          content:
            application/json:
              schema:
                {}

components:
  schemas:
    FeatureStateUpdate:
      type: object
      properties:
        value:
          description: "the new value"
        updateValue:
          type: boolean
          description: "indicates whether you are trying to update the value, as value can be null"
        lock:
          description: "set only if you wish to lock or unlock, otherwise null"
          type: boolean
    SSEResultState:
      type: string
      enum:
        - ack
        - bye
        - failure
        - features
        - feature
        - delete_feature
    Environment:
      properties:
        id:
          type: string
        features:
          type: array
          items:
            $ref: "#/components/schemas/FeatureState"
    FeatureState:
      required:
        - name
      properties:
        id:
          type: string
        key:
          type: string
        l:
          description: "Is this feature locked. Usually this doesn't matter because the value is the value, but for FeatureInterceptors it can matter."
          type: boolean
        version:
          description: "The version of the feature, this allows features to change values and it means we don't trigger events"
          type: integer
          format: int64
        type:
          $ref: "#/components/schemas/FeatureValueType"
        value:
          description: "the current value"
        environmentId:
          description: "This field is filled in from the client side in the GET api as the GET api is able to request multiple environments.
                        It is never passed from the server, as an array of feature states is wrapped in an environment."
          type: string
        strategies:
          type: array
          items:
            $ref: "#/components/schemas/RolloutStrategy"


