openapi: 3.0.1
info:
  title: FeatureServiceApi
  description: This describes the API clients use for accessing features
  version: "1.1.1"
paths:
  /features/{sdkUrl}/{featureKey}:
    put:
      tags:
        - FeatureService
      parameters:
        - name: sdkUrl
          in: path
          description: "The SDK key for the environment and service account"
          schema:
            type: string
        - name: featureKey
          in: path
          description: "The key you wish to update/action"
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FeatureStateUpdate"
      description: "Gets a list of features and their states. This is not accurate as it returns a text/event-stream."
      operationId: allFeatures
      responses:
        "200":
          description: gets all of the features
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FeatureState"
components:
  schemas:
    FeatureStateUpdate:
      type: object
      properties:
        value:
          description: "the new value"
        updateValue:
          type: boolean
          description: "indicates whether you are trying to update the value, as value can be null"
        lock:
          description: "set only if you wish to lock or unlock, otherwise null"
          type: boolean
    SSEResultState:
      type: string
      enum:
        - ack
        - bye
        - failure
        - features
        - feature
        - delete_feature
    FeatureState:
      required:
        - name
      properties:
        id:
          type: string
        key:
          type: string
        version:
          type: integer
          format: int64
        type:
          $ref: "#/components/schemas/FeatureValueType"
        value:
          description: "the current value"
        strategy:
          $ref: "#/components/schemas/Strategy"
    Strategy:
#      description: "This tells the client which strategy for roll out is being used".
      required:
        - name
      properties:
        name:
          $ref: "#/components/schemas/StrategyNameType"
        value:
          description: "this value is used if it is a simple attribute or percentage. If it is more complex then the pairs are passed"
        pairs:
          type: array
          items:
            $ref: "#/components/schemas/StrategyPair"
    StrategyNameType:
      type: string
      enum:
        - ATTRIBUTE
        - PERCENTAGE
    StrategyPair:
 #     description: "This is simply information the feature wishes to pass"
      required:
        - name
      properties:
        name:
          type: string
        value:
          type: string

