name: build adocs

on:
  push:
    branches:
      - master
jobs:
  adoc_build:
    runs-on: ubuntu-18.04
    name: docs
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get build container
        id: adocbuild
        uses: ./doc-gen
      - name: Print execution time
        run: echo "Time ${{ steps.adocbuild.outputs.timestamp }}"
      - name: Deploy docs to ghpages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./doc-gen/target/generated-docs
          external_repository: featurehub-io/featurehub-io
          publish_branch: master
          cname: docs.featurehub.io
