# This is a basic workflow to help you get started with Actions

name: client-typescript-core build and test

# Controls when the action will run. 
on:
  # Triggers the workflow on push request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build and unit test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Install dependencies    
        run: npm install
        working-directory: sdks/typescript/client-typescript-core
      - name: Build and test
        run: npm run test
        working-directory: sdks/typescript/client-typescript-core
